data = [{'created_at': 'Mon Oct 22 03:02:06 +0000 2018', 'id': 1054206233593499648, 'id_str': '1054206233593499648',
         'text': 'With his 4th quarter TD pass to Tyreek Hill, Patrick Mahomes passed Kurt Warner for the most TD passes in any playe… https://t.co/wLwZYTOLQF',
         'truncated': True, 'entities': {'hashtags': [], 'symbols': [], 'user_mentions': [], 'urls': [
        {'url': 'https://t.co/wLwZYTOLQF', 'expanded_url': 'https://twitter.com/i/web/status/1054206233593499648',
         'display_url': 'twitter.com/i/web/status/1…', 'indices': [117, 140]}]},
         'metadata': {'result_type': 'popular', 'iso_language_code': 'en'},
         'source': '<a href="https://www.spredfast.com/" rel="nofollow">Spredfast app</a>',
         'in_reply_to_status_id': None, 'in_reply_to_status_id_str': None, 'in_reply_to_user_id': None,
         'in_reply_to_user_id_str': None, 'in_reply_to_screen_name': None,
         'user': {'id': 26257166, 'id_str': '26257166', 'name': 'SportsCenter', 'screen_name': 'SportsCenter',
                  'location': '', 'description': 'Download the ESPN App ⬇️', 'url': 'https://t.co/RqqkIx8GI7',
                  'entities': {'url': {'urls': [
                      {'url': 'https://t.co/RqqkIx8GI7', 'expanded_url': 'http://es.pn/app', 'display_url': 'es.pn/app',
                       'indices': [0, 23]}]}, 'description': {'urls': []}}, 'protected': False,
                  'followers_count': 35422512, 'friends_count': 1659, 'listed_count': 45452,
                  'created_at': 'Tue Mar 24 15:28:02 +0000 2009', 'favourites_count': 1113, 'utc_offset': None,
                  'time_zone': None, 'geo_enabled': True, 'verified': True, 'statuses_count': 105439, 'lang': 'en',
                  'contributors_enabled': False, 'is_translator': False, 'is_translation_enabled': True,
                  'profile_background_color': '131516',
                  'profile_background_image_url': 'http://abs.twimg.com/images/themes/theme14/bg.gif',
                  'profile_background_image_url_https': 'https://abs.twimg.com/images/themes/theme14/bg.gif',
                  'profile_background_tile': True,
                  'profile_image_url': 'http://pbs.twimg.com/profile_images/875363787867652096/JVsTbdmb_normal.jpg',
                  'profile_image_url_https': 'https://pbs.twimg.com/profile_images/875363787867652096/JVsTbdmb_normal.jpg',
                  'profile_banner_url': 'https://pbs.twimg.com/profile_banners/26257166/1526923497',
                  'profile_link_color': '009999', 'profile_sidebar_border_color': '000000',
                  'profile_sidebar_fill_color': 'EFEFEF', 'profile_text_color': '333333',
                  'profile_use_background_image': True, 'has_extended_profile': False, 'default_profile': False,
                  'default_profile_image': False, 'following': False, 'follow_request_sent': False,
                  'notifications': False, 'translator_type': 'regular'}, 'geo': None, 'coordinates': None,
         'place': None, 'contributors': None, 'is_quote_status': False, 'retweet_count': 1248, 'favorite_count': 6774,
         'favorited': False, 'retweeted': False, 'possibly_sensitive': False, 'lang': 'en'},
        {'created_at': 'Sat Oct 20 23:03:12 +0000 2018', 'id': 1053783723550814208, 'id_str': '1053783723550814208',
         'text': "So Tyreek Hill's got 99 speed in @EAMaddenNFL now.\n\nNext up: Peyton Manning?\n\nThrowing it back to the QB's longest… https://t.co/XxpAcbVJTA",
         'truncated': True, 'entities': {'hashtags': [], 'symbols': [], 'user_mentions': [
            {'screen_name': 'EAMaddenNFL', 'name': '#WeAreMadden', 'id': 50096544, 'id_str': '50096544',
             'indices': [33, 45]}], 'urls': [
            {'url': 'https://t.co/XxpAcbVJTA', 'expanded_url': 'https://twitter.com/i/web/status/1053783723550814208',
             'display_url': 'twitter.com/i/web/status/1…', 'indices': [116, 139]}]},
         'metadata': {'result_type': 'popular', 'iso_language_code': 'en'},
         'source': '<a href="https://studio.twitter.com" rel="nofollow">Media Studio</a>',
         'in_reply_to_status_id': None, 'in_reply_to_status_id_str': None, 'in_reply_to_user_id': None,
         'in_reply_to_user_id_str': None, 'in_reply_to_screen_name': None,
         'user': {'id': 62610707, 'id_str': '62610707', 'name': 'NFL Throwback', 'screen_name': 'nflthrowback',
                  'location': 'NFL Archive',
                  'description': 'Taking a deep dive through the NFL archive. Who knows what we will find?',
                  'url': 'https://t.co/vIikzemJNp', 'entities': {'url': {'urls': [
                 {'url': 'https://t.co/vIikzemJNp', 'expanded_url': 'http://www.nfl.com', 'display_url': 'nfl.com',
                  'indices': [0, 23]}]}, 'description': {'urls': []}}, 'protected': False, 'followers_count': 62576,
                  'friends_count': 708, 'listed_count': 1137, 'created_at': 'Mon Aug 03 20:16:47 +0000 2009',
                  'favourites_count': 588, 'utc_offset': None, 'time_zone': None, 'geo_enabled': True, 'verified': True,
                  'statuses_count': 3119, 'lang': 'en', 'contributors_enabled': False, 'is_translator': False,
                  'is_translation_enabled': False, 'profile_background_color': 'C0DEED',
                  'profile_background_image_url': 'http://abs.twimg.com/images/themes/theme1/bg.png',
                  'profile_background_image_url_https': 'https://abs.twimg.com/images/themes/theme1/bg.png',
                  'profile_background_tile': True,
                  'profile_image_url': 'http://pbs.twimg.com/profile_images/1035576991078961152/QmPvgxtR_normal.jpg',
                  'profile_image_url_https': 'https://pbs.twimg.com/profile_images/1035576991078961152/QmPvgxtR_normal.jpg',
                  'profile_banner_url': 'https://pbs.twimg.com/profile_banners/62610707/1536077930',
                  'profile_link_color': '0084B4', 'profile_sidebar_border_color': 'FFFFFF',
                  'profile_sidebar_fill_color': 'DDEEF6', 'profile_text_color': '333333',
                  'profile_use_background_image': True, 'has_extended_profile': False, 'default_profile': False,
                  'default_profile_image': False, 'following': False, 'follow_request_sent': False,
                  'notifications': False, 'translator_type': 'none'}, 'geo': None, 'coordinates': None, 'place': None,
         'contributors': None, 'is_quote_status': False, 'retweet_count': 290, 'favorite_count': 1406,
         'favorited': False, 'retweeted': False, 'possibly_sensitive': False, 'lang': 'en'},
        {'created_at': 'Mon Oct 22 01:18:28 +0000 2018', 'id': 1054180149770375168, 'id_str': '1054180149770375168',
         'text': 'trying to stop kareem hunt while containing both travis kelce and tyreek hill is like one of those math problems th… https://t.co/KRVZQ7gTj9',
         'truncated': True, 'entities': {'hashtags': [], 'symbols': [], 'user_mentions': [], 'urls': [
            {'url': 'https://t.co/KRVZQ7gTj9', 'expanded_url': 'https://twitter.com/i/web/status/1054180149770375168',
             'display_url': 'twitter.com/i/web/status/1…', 'indices': [117, 140]}]},
         'metadata': {'result_type': 'popular', 'iso_language_code': 'en'},
         'source': '<a href="http://twitter.com" rel="nofollow">Twitter Web Client</a>', 'in_reply_to_status_id': None,
         'in_reply_to_status_id_str': None, 'in_reply_to_user_id': None, 'in_reply_to_user_id_str': None,
         'in_reply_to_screen_name': None,
         'user': {'id': 95975081, 'id_str': '95975081', 'name': 'Mina Kimes', 'screen_name': 'minakimes',
                  'location': 'Los Angeles, CA',
                  'description': 'Senior Writer @ ESPN The Magazine, crossword enthusiast, hater of the goal line fade',
                  'url': 'https://t.co/OIS0spxCLo', 'entities': {'url': {'urls': [
                 {'url': 'https://t.co/OIS0spxCLo', 'expanded_url': 'http://minakimes.tumblr.com/sports',
                  'display_url': 'minakimes.tumblr.com/sports', 'indices': [0, 23]}]}, 'description': {'urls': []}},
                  'protected': False, 'followers_count': 227983, 'friends_count': 1089, 'listed_count': 2524,
                  'created_at': 'Thu Dec 10 20:18:22 +0000 2009', 'favourites_count': 59189, 'utc_offset': None,
                  'time_zone': None, 'geo_enabled': True, 'verified': True, 'statuses_count': 45370, 'lang': 'en',
                  'contributors_enabled': False, 'is_translator': False, 'is_translation_enabled': False,
                  'profile_background_color': '000000',
                  'profile_background_image_url': 'http://abs.twimg.com/images/themes/theme6/bg.gif',
                  'profile_background_image_url_https': 'https://abs.twimg.com/images/themes/theme6/bg.gif',
                  'profile_background_tile': True,
                  'profile_image_url': 'http://pbs.twimg.com/profile_images/1035943502448738305/4odRC_pu_normal.jpg',
                  'profile_image_url_https': 'https://pbs.twimg.com/profile_images/1035943502448738305/4odRC_pu_normal.jpg',
                  'profile_banner_url': 'https://pbs.twimg.com/profile_banners/95975081/1529549060',
                  'profile_link_color': '13319E', 'profile_sidebar_border_color': '000000',
                  'profile_sidebar_fill_color': '9EC3D9', 'profile_text_color': '030303',
                  'profile_use_background_image': True, 'has_extended_profile': False, 'default_profile': False,
                  'default_profile_image': False, 'following': False, 'follow_request_sent': False,
                  'notifications': False, 'translator_type': 'none'}, 'geo': None, 'coordinates': None, 'place': None,
         'contributors': None, 'is_quote_status': False, 'retweet_count': 229, 'favorite_count': 2067,
         'favorited': False, 'retweeted': False, 'lang': 'en'},
        {'created_at': 'Mon Oct 22 00:21:33 +0000 2018', 'id': 1054165827006726144, 'id_str': '1054165827006726144',
         'text': "Tyreek Hill and Travis Kelce win the introductions. Slight edge to Hill for breaking out the Ray Lewis dance. It's… https://t.co/eXzUyX0sZF",
         'truncated': True, 'entities': {'hashtags': [], 'symbols': [], 'user_mentions': [], 'urls': [
            {'url': 'https://t.co/eXzUyX0sZF', 'expanded_url': 'https://twitter.com/i/web/status/1054165827006726144',
             'display_url': 'twitter.com/i/web/status/1…', 'indices': [116, 139]}]},
         'metadata': {'result_type': 'popular', 'iso_language_code': 'en'},
         'source': '<a href="http://twitter.com" rel="nofollow">Twitter Web Client</a>', 'in_reply_to_status_id': None,
         'in_reply_to_status_id_str': None, 'in_reply_to_user_id': None, 'in_reply_to_user_id_str': None,
         'in_reply_to_screen_name': None,
         'user': {'id': 350611666, 'id_str': '350611666', 'name': 'Tyler Greever', 'screen_name': 'WIBWTyler',
                  'location': 'Topeka, KS',
                  'description': 'Sports Director @wibw. @Mizzou alum. VA born and bred. Views = mine. A new addition to the art of the old code.',
                  'url': 'https://t.co/KBN32fUQGx', 'entities': {'url': {'urls': [
                 {'url': 'https://t.co/KBN32fUQGx', 'expanded_url': 'https://www.wibw.com/', 'display_url': 'wibw.com',
                  'indices': [0, 23]}]}, 'description': {'urls': []}}, 'protected': False, 'followers_count': 2501,
                  'friends_count': 924, 'listed_count': 53, 'created_at': 'Mon Aug 08 01:49:13 +0000 2011',
                  'favourites_count': 29461, 'utc_offset': None, 'time_zone': None, 'geo_enabled': True,
                  'verified': True, 'statuses_count': 90425, 'lang': 'en', 'contributors_enabled': False,
                  'is_translator': False, 'is_translation_enabled': False, 'profile_background_color': '000000',
                  'profile_background_image_url': 'http://abs.twimg.com/images/themes/theme1/bg.png',
                  'profile_background_image_url_https': 'https://abs.twimg.com/images/themes/theme1/bg.png',
                  'profile_background_tile': False,
                  'profile_image_url': 'http://pbs.twimg.com/profile_images/1052411427003219968/nOAbufr8_normal.jpg',
                  'profile_image_url_https': 'https://pbs.twimg.com/profile_images/1052411427003219968/nOAbufr8_normal.jpg',
                  'profile_banner_url': 'https://pbs.twimg.com/profile_banners/350611666/1528488652',
                  'profile_link_color': '270485', 'profile_sidebar_border_color': 'FFFFFF',
                  'profile_sidebar_fill_color': 'F6F6F6', 'profile_text_color': '333333',
                  'profile_use_background_image': False, 'has_extended_profile': True, 'default_profile': False,
                  'default_profile_image': False, 'following': False, 'follow_request_sent': False,
                  'notifications': False, 'translator_type': 'none'}, 'geo': None, 'coordinates': None, 'place': None,
         'contributors': None, 'is_quote_status': False, 'retweet_count': 41, 'favorite_count': 123, 'favorited': False,
         'retweeted': False, 'possibly_sensitive': False, 'lang': 'en'},
        {'created_at': 'Mon Oct 22 03:11:53 +0000 2018', 'id': 1054208692709666817, 'id_str': '1054208692709666817',
         'text': "A nod to the original #HalloweenMovie and Michael Myers from the Chiefs' Tyreek Hill (@cheetah) on his touchdown ce… https://t.co/SB7lSQalTF",
         'truncated': True, 'entities': {'hashtags': [{'text': 'HalloweenMovie', 'indices': [22, 37]}], 'symbols': [],
                                         'user_mentions': [{'screen_name': 'cheetah', 'name': 'Ty Hill', 'id': 83738272,
                                                            'id_str': '83738272', 'indices': [86, 94]}], 'urls': [
                {'url': 'https://t.co/SB7lSQalTF',
                 'expanded_url': 'https://twitter.com/i/web/status/1054208692709666817',
                 'display_url': 'twitter.com/i/web/status/1…', 'indices': [117, 140]}]},
         'metadata': {'result_type': 'popular', 'iso_language_code': 'en'},
         'source': '<a href="http://twitter.com" rel="nofollow">Twitter Web Client</a>', 'in_reply_to_status_id': None,
         'in_reply_to_status_id_str': None, 'in_reply_to_user_id': None, 'in_reply_to_user_id_str': None,
         'in_reply_to_screen_name': None,
         'user': {'id': 894899924051136512, 'id_str': '894899924051136512', 'name': 'Lights, Camera, Pod',
                  'screen_name': 'LightsCameraPod', 'location': 'United States',
                  'description': "Barstool's movie brand/podcast featuring @Trillballins, @JeffDLowe & @KenJac // Subscribe to the podcast below",
                  'url': 'https://t.co/EluNDSADTq', 'entities': {'url': {'urls': [{'url': 'https://t.co/EluNDSADTq',
                                                                                   'expanded_url': 'https://itunes.apple.com/us/podcast/lights-camera-podcast/id1279516571?mt=2',
                                                                                   'display_url': 'itunes.apple.com/us/podcast/lig…',
                                                                                   'indices': [0, 23]}]},
                                                                 'description': {'urls': []}}, 'protected': False,
                  'followers_count': 23721, 'friends_count': 373, 'listed_count': 95,
                  'created_at': 'Tue Aug 08 12:35:43 +0000 2017', 'favourites_count': 2982, 'utc_offset': None,
                  'time_zone': None, 'geo_enabled': True, 'verified': True, 'statuses_count': 6815, 'lang': 'en',
                  'contributors_enabled': False, 'is_translator': False, 'is_translation_enabled': False,
                  'profile_background_color': '000000',
                  'profile_background_image_url': 'http://abs.twimg.com/images/themes/theme1/bg.png',
                  'profile_background_image_url_https': 'https://abs.twimg.com/images/themes/theme1/bg.png',
                  'profile_background_tile': False,
                  'profile_image_url': 'http://pbs.twimg.com/profile_images/996615374627065856/P2OJRP2h_normal.jpg',
                  'profile_image_url_https': 'https://pbs.twimg.com/profile_images/996615374627065856/P2OJRP2h_normal.jpg',
                  'profile_banner_url': 'https://pbs.twimg.com/profile_banners/894899924051136512/1526411364',
                  'profile_link_color': '5F3817', 'profile_sidebar_border_color': '000000',
                  'profile_sidebar_fill_color': '000000', 'profile_text_color': '000000',
                  'profile_use_background_image': False, 'has_extended_profile': False, 'default_profile': False,
                  'default_profile_image': False, 'following': False, 'follow_request_sent': False,
                  'notifications': False, 'translator_type': 'none'}, 'geo': None, 'coordinates': None, 'place': None,
         'contributors': None, 'is_quote_status': False, 'retweet_count': 47, 'favorite_count': 241, 'favorited': False,
         'retweeted': False, 'possibly_sensitive': False, 'lang': 'en'},
        {'created_at': 'Mon Oct 22 04:46:57 +0000 2018', 'id': 1054232617556606977, 'id_str': '1054232617556606977',
         'text': 'The Chiefs reminded us of everything that fans truly love most about football in their blowout victory against the… https://t.co/jrmuMDLESM',
         'truncated': True, 'entities': {'hashtags': [], 'symbols': [], 'user_mentions': [], 'urls': [
            {'url': 'https://t.co/jrmuMDLESM', 'expanded_url': 'https://twitter.com/i/web/status/1054232617556606977',
             'display_url': 'twitter.com/i/web/status/1…', 'indices': [116, 139]}]},
         'metadata': {'result_type': 'popular', 'iso_language_code': 'en'},
         'source': '<a href="http://www.socialflow.com" rel="nofollow">SocialFlow</a>', 'in_reply_to_status_id': None,
         'in_reply_to_status_id_str': None, 'in_reply_to_user_id': None, 'in_reply_to_user_id_str': None,
         'in_reply_to_screen_name': None,
         'user': {'id': 1397342508, 'id_str': '1397342508', 'name': 'The MMQB', 'screen_name': 'theMMQB',
                  'location': '',
                  'description': "All things NFL, all the time. It's like having a coach speaking directly into your helmet",
                  'url': 'https://t.co/QVnHLMvW0l', 'entities': {'url': {'urls': [
                 {'url': 'https://t.co/QVnHLMvW0l', 'expanded_url': 'http://TheMMQB.com', 'display_url': 'TheMMQB.com',
                  'indices': [0, 23]}]}, 'description': {'urls': []}}, 'protected': False, 'followers_count': 168461,
                  'friends_count': 725, 'listed_count': 3273, 'created_at': 'Thu May 02 14:38:52 +0000 2013',
                  'favourites_count': 1964, 'utc_offset': None, 'time_zone': None, 'geo_enabled': True,
                  'verified': True, 'statuses_count': 33113, 'lang': 'en', 'contributors_enabled': False,
                  'is_translator': False, 'is_translation_enabled': False, 'profile_background_color': '2E2E2E',
                  'profile_background_image_url': 'http://abs.twimg.com/images/themes/theme1/bg.png',
                  'profile_background_image_url_https': 'https://abs.twimg.com/images/themes/theme1/bg.png',
                  'profile_background_tile': False,
                  'profile_image_url': 'http://pbs.twimg.com/profile_images/820083470647042053/OY25iVkf_normal.jpg',
                  'profile_image_url_https': 'https://pbs.twimg.com/profile_images/820083470647042053/OY25iVkf_normal.jpg',
                  'profile_banner_url': 'https://pbs.twimg.com/profile_banners/1397342508/1484349974',
                  'profile_link_color': 'EF2626', 'profile_sidebar_border_color': 'FFFFFF',
                  'profile_sidebar_fill_color': 'DDEEF6', 'profile_text_color': '333333',
                  'profile_use_background_image': True, 'has_extended_profile': False, 'default_profile': False,
                  'default_profile_image': False, 'following': False, 'follow_request_sent': False,
                  'notifications': False, 'translator_type': 'none'}, 'geo': None, 'coordinates': None, 'place': None,
         'contributors': None, 'is_quote_status': False, 'retweet_count': 45, 'favorite_count': 118, 'favorited': False,
         'retweeted': False, 'possibly_sensitive': False, 'lang': 'en'},
        {'created_at': 'Mon Oct 15 17:58:14 +0000 2018', 'id': 1051895036370145280, 'id_str': '1051895036370145280',
         'text': 'Patriots have identified the fan who threw beer at Tyreek Hill &amp; banned them from all future events at Gillette Sta… https://t.co/woxvMUCnte',
         'truncated': True, 'entities': {'hashtags': [], 'symbols': [], 'user_mentions': [], 'urls': [
            {'url': 'https://t.co/woxvMUCnte', 'expanded_url': 'https://twitter.com/i/web/status/1051895036370145280',
             'display_url': 'twitter.com/i/web/status/1…', 'indices': [121, 144]}]},
         'metadata': {'result_type': 'popular', 'iso_language_code': 'en'},
         'source': '<a href="https://about.twitter.com/products/tweetdeck" rel="nofollow">TweetDeck</a>',
         'in_reply_to_status_id': None, 'in_reply_to_status_id_str': None, 'in_reply_to_user_id': None,
         'in_reply_to_user_id_str': None, 'in_reply_to_screen_name': None,
         'user': {'id': 890891, 'id_str': '890891', 'name': 'Bleacher Report', 'screen_name': 'BleacherReport',
                  'location': '', 'description': 'Get the Free B/R App', 'url': 'https://t.co/CFXD5md1KQ', 'entities': {
                 'url': {'urls': [
                     {'url': 'https://t.co/CFXD5md1KQ', 'expanded_url': 'https://br.app.link/get-the-BR-app',
                      'display_url': 'br.app.link/get-the-BR-app', 'indices': [0, 23]}]}, 'description': {'urls': []}},
                  'protected': False, 'followers_count': 6741917, 'friends_count': 623, 'listed_count': 17499,
                  'created_at': 'Sat Mar 10 23:52:36 +0000 2007', 'favourites_count': 181, 'utc_offset': None,
                  'time_zone': None, 'geo_enabled': True, 'verified': True, 'statuses_count': 99764, 'lang': 'en',
                  'contributors_enabled': False, 'is_translator': False, 'is_translation_enabled': True,
                  'profile_background_color': '444444',
                  'profile_background_image_url': 'http://abs.twimg.com/images/themes/theme14/bg.gif',
                  'profile_background_image_url_https': 'https://abs.twimg.com/images/themes/theme14/bg.gif',
                  'profile_background_tile': False,
                  'profile_image_url': 'http://pbs.twimg.com/profile_images/854430488777379840/zFdLhwbT_normal.jpg',
                  'profile_image_url_https': 'https://pbs.twimg.com/profile_images/854430488777379840/zFdLhwbT_normal.jpg',
                  'profile_banner_url': 'https://pbs.twimg.com/profile_banners/890891/1523712004',
                  'profile_link_color': '000000', 'profile_sidebar_border_color': 'FFFFFF',
                  'profile_sidebar_fill_color': 'EFEFEF', 'profile_text_color': '333333',
                  'profile_use_background_image': False, 'has_extended_profile': False, 'default_profile': False,
                  'default_profile_image': False, 'following': False, 'follow_request_sent': False,
                  'notifications': False, 'translator_type': 'none'}, 'geo': None, 'coordinates': None, 'place': None,
         'contributors': None, 'is_quote_status': True, 'quoted_status_id': 1051677009305198592,
         'quoted_status_id_str': '1051677009305198592',
         'quoted_status': {'created_at': 'Mon Oct 15 03:31:52 +0000 2018', 'id': 1051677009305198592,
                           'id_str': '1051677009305198592',
                           'text': 'Pats fans flipped off Tyreek Hill and poured beer on him after his TD... https://t.co/8i8zWNZJnD',
                           'truncated': False,
                           'entities': {'hashtags': [], 'symbols': [], 'user_mentions': [], 'urls': [], 'media': [
                               {'id': 1051676217689034752, 'id_str': '1051676217689034752', 'indices': [73, 96],
                                'media_url': 'http://pbs.twimg.com/media/DphN8q4U0AAZlK2.jpg',
                                'media_url_https': 'https://pbs.twimg.com/media/DphN8q4U0AAZlK2.jpg',
                                'url': 'https://t.co/8i8zWNZJnD', 'display_url': 'pic.twitter.com/8i8zWNZJnD',
                                'expanded_url': 'https://twitter.com/BleacherReport/status/1051677009305198592/photo/1',
                                'type': 'photo', 'sizes': {'thumb': {'w': 150, 'h': 150, 'resize': 'crop'},
                                                           'medium': {'w': 1024, 'h': 905, 'resize': 'fit'},
                                                           'small': {'w': 680, 'h': 601, 'resize': 'fit'},
                                                           'large': {'w': 1024, 'h': 905, 'resize': 'fit'}}}]},
                           'extended_entities': {'media': [
                               {'id': 1051676217689034752, 'id_str': '1051676217689034752', 'indices': [73, 96],
                                'media_url': 'http://pbs.twimg.com/media/DphN8q4U0AAZlK2.jpg',
                                'media_url_https': 'https://pbs.twimg.com/media/DphN8q4U0AAZlK2.jpg',
                                'url': 'https://t.co/8i8zWNZJnD', 'display_url': 'pic.twitter.com/8i8zWNZJnD',
                                'expanded_url': 'https://twitter.com/BleacherReport/status/1051677009305198592/photo/1',
                                'type': 'photo', 'sizes': {'thumb': {'w': 150, 'h': 150, 'resize': 'crop'},
                                                           'medium': {'w': 1024, 'h': 905, 'resize': 'fit'},
                                                           'small': {'w': 680, 'h': 601, 'resize': 'fit'},
                                                           'large': {'w': 1024, 'h': 905, 'resize': 'fit'}}}]},
                           'metadata': {'result_type': 'popular', 'iso_language_code': 'en'},
                           'source': '<a href="https://about.twitter.com/products/tweetdeck" rel="nofollow">TweetDeck</a>',
                           'in_reply_to_status_id': None, 'in_reply_to_status_id_str': None,
                           'in_reply_to_user_id': None, 'in_reply_to_user_id_str': None,
                           'in_reply_to_screen_name': None,
                           'user': {'id': 890891, 'id_str': '890891', 'name': 'Bleacher Report',
                                    'screen_name': 'BleacherReport', 'location': '',
                                    'description': 'Get the Free B/R App', 'url': 'https://t.co/CFXD5md1KQ',
                                    'entities': {'url': {'urls': [{'url': 'https://t.co/CFXD5md1KQ',
                                                                   'expanded_url': 'https://br.app.link/get-the-BR-app',
                                                                   'display_url': 'br.app.link/get-the-BR-app',
                                                                   'indices': [0, 23]}]}, 'description': {'urls': []}},
                                    'protected': False, 'followers_count': 6741917, 'friends_count': 623,
                                    'listed_count': 17499, 'created_at': 'Sat Mar 10 23:52:36 +0000 2007',
                                    'favourites_count': 181, 'utc_offset': None, 'time_zone': None, 'geo_enabled': True,
                                    'verified': True, 'statuses_count': 99764, 'lang': 'en',
                                    'contributors_enabled': False, 'is_translator': False,
                                    'is_translation_enabled': True, 'profile_background_color': '444444',
                                    'profile_background_image_url': 'http://abs.twimg.com/images/themes/theme14/bg.gif',
                                    'profile_background_image_url_https': 'https://abs.twimg.com/images/themes/theme14/bg.gif',
                                    'profile_background_tile': False,
                                    'profile_image_url': 'http://pbs.twimg.com/profile_images/854430488777379840/zFdLhwbT_normal.jpg',
                                    'profile_image_url_https': 'https://pbs.twimg.com/profile_images/854430488777379840/zFdLhwbT_normal.jpg',
                                    'profile_banner_url': 'https://pbs.twimg.com/profile_banners/890891/1523712004',
                                    'profile_link_color': '000000', 'profile_sidebar_border_color': 'FFFFFF',
                                    'profile_sidebar_fill_color': 'EFEFEF', 'profile_text_color': '333333',
                                    'profile_use_background_image': False, 'has_extended_profile': False,
                                    'default_profile': False, 'default_profile_image': False, 'following': False,
                                    'follow_request_sent': False, 'notifications': False, 'translator_type': 'none'},
                           'geo': None, 'coordinates': None, 'place': None, 'contributors': None,
                           'is_quote_status': False, 'retweet_count': 1272, 'favorite_count': 5794, 'favorited': False,
                           'retweeted': False, 'possibly_sensitive': False, 'lang': 'en'}, 'retweet_count': 8664,
         'favorite_count': 42629, 'favorited': False, 'retweeted': False, 'possibly_sensitive': False, 'lang': 'en'},
        {'created_at': 'Mon Oct 22 04:39:12 +0000 2018', 'id': 1054230668878725121, 'id_str': '1054230668878725121',
         'text': 'Eric Fisher on "reviving" Tyreek Hill: "I gave him CPR, and he came back to life." Says he hopes it was on TV. "Tha… https://t.co/JUeELmQDaX',
         'truncated': True, 'entities': {'hashtags': [], 'symbols': [], 'user_mentions': [], 'urls': [
            {'url': 'https://t.co/JUeELmQDaX', 'expanded_url': 'https://twitter.com/i/web/status/1054230668878725121',
             'display_url': 'twitter.com/i/web/status/1…', 'indices': [117, 140]}]},
         'metadata': {'result_type': 'popular', 'iso_language_code': 'en'},
         'source': '<a href="http://twitter.com" rel="nofollow">Twitter Web Client</a>', 'in_reply_to_status_id': None,
         'in_reply_to_status_id_str': None, 'in_reply_to_user_id': None, 'in_reply_to_user_id_str': None,
         'in_reply_to_screen_name': None,
         'user': {'id': 36565914, 'id_str': '36565914', 'name': 'Vahe Gregorian', 'screen_name': 'vgregorian',
                  'location': 'Kansas City',
                  'description': 'Sports columnist for the @KCStar and https://t.co/uN3S4W3AKh',
                  'url': 'https://t.co/pgllbyvnCU', 'entities': {'url': {'urls': [{'url': 'https://t.co/pgllbyvnCU',
                                                                                   'expanded_url': 'http://www.kansascity.com/sports/spt-columns-blogs/vahe-gregorian/',
                                                                                   'display_url': 'kansascity.com/sports/spt-col…',
                                                                                   'indices': [0, 23]}]},
                                                                 'description': {'urls': [
                                                                     {'url': 'https://t.co/uN3S4W3AKh',
                                                                      'expanded_url': 'http://kansascity.com',
                                                                      'display_url': 'kansascity.com',
                                                                      'indices': [37, 60]}]}}, 'protected': False,
                  'followers_count': 23095, 'friends_count': 1975, 'listed_count': 528,
                  'created_at': 'Thu Apr 30 02:20:33 +0000 2009', 'favourites_count': 8948, 'utc_offset': None,
                  'time_zone': None, 'geo_enabled': False, 'verified': True, 'statuses_count': 27637, 'lang': 'en',
                  'contributors_enabled': False, 'is_translator': False, 'is_translation_enabled': False,
                  'profile_background_color': 'C0DEED',
                  'profile_background_image_url': 'http://abs.twimg.com/images/themes/theme1/bg.png',
                  'profile_background_image_url_https': 'https://abs.twimg.com/images/themes/theme1/bg.png',
                  'profile_background_tile': False,
                  'profile_image_url': 'http://pbs.twimg.com/profile_images/1052659845185323010/lGDgjxYu_normal.jpg',
                  'profile_image_url_https': 'https://pbs.twimg.com/profile_images/1052659845185323010/lGDgjxYu_normal.jpg',
                  'profile_banner_url': 'https://pbs.twimg.com/profile_banners/36565914/1468868876',
                  'profile_link_color': '1DA1F2', 'profile_sidebar_border_color': 'C0DEED',
                  'profile_sidebar_fill_color': 'DDEEF6', 'profile_text_color': '333333',
                  'profile_use_background_image': True, 'has_extended_profile': False, 'default_profile': True,
                  'default_profile_image': False, 'following': False, 'follow_request_sent': False,
                  'notifications': False, 'translator_type': 'none'}, 'geo': None, 'coordinates': None, 'place': None,
         'contributors': None, 'is_quote_status': True, 'quoted_status_id': 1054207848769568773,
         'quoted_status_id_str': '1054207848769568773',
         'quoted_status': {'created_at': 'Mon Oct 22 03:08:32 +0000 2018', 'id': 1054207848769568773,
                           'id_str': '1054207848769568773',
                           'text': "🎵\xa0Stayin' alive, stayin' alive https://t.co/JN5fajn02s", 'truncated': False,
                           'entities': {'hashtags': [], 'symbols': [], 'user_mentions': [], 'urls': [], 'media': [
                               {'id': 1054207338339397632, 'id_str': '1054207338339397632', 'indices': [31, 54],
                                'media_url': 'http://pbs.twimg.com/ext_tw_video_thumb/1054207338339397632/pu/img/pp0b2VXzgOuygxun.jpg',
                                'media_url_https': 'https://pbs.twimg.com/ext_tw_video_thumb/1054207338339397632/pu/img/pp0b2VXzgOuygxun.jpg',
                                'url': 'https://t.co/JN5fajn02s', 'display_url': 'pic.twitter.com/JN5fajn02s',
                                'expanded_url': 'https://twitter.com/Chiefs/status/1054207848769568773/video/1',
                                'type': 'photo', 'sizes': {'thumb': {'w': 150, 'h': 150, 'resize': 'crop'},
                                                           'medium': {'w': 1200, 'h': 675, 'resize': 'fit'},
                                                           'small': {'w': 680, 'h': 383, 'resize': 'fit'},
                                                           'large': {'w': 1280, 'h': 720, 'resize': 'fit'}}}]},
                           'extended_entities': {'media': [
                               {'id': 1054207338339397632, 'id_str': '1054207338339397632', 'indices': [31, 54],
                                'media_url': 'http://pbs.twimg.com/ext_tw_video_thumb/1054207338339397632/pu/img/pp0b2VXzgOuygxun.jpg',
                                'media_url_https': 'https://pbs.twimg.com/ext_tw_video_thumb/1054207338339397632/pu/img/pp0b2VXzgOuygxun.jpg',
                                'url': 'https://t.co/JN5fajn02s', 'display_url': 'pic.twitter.com/JN5fajn02s',
                                'expanded_url': 'https://twitter.com/Chiefs/status/1054207848769568773/video/1',
                                'type': 'video', 'sizes': {'thumb': {'w': 150, 'h': 150, 'resize': 'crop'},
                                                           'medium': {'w': 1200, 'h': 675, 'resize': 'fit'},
                                                           'small': {'w': 680, 'h': 383, 'resize': 'fit'},
                                                           'large': {'w': 1280, 'h': 720, 'resize': 'fit'}},
                                'video_info': {'aspect_ratio': [16, 9], 'duration_millis': 5873, 'variants': [
                                    {'bitrate': 832000, 'content_type': 'video/mp4',
                                     'url': 'https://video.twimg.com/ext_tw_video/1054207338339397632/pu/vid/640x360/dPFp2trF0Xk5h5Ch.mp4?tag=5'},
                                    {'bitrate': 256000, 'content_type': 'video/mp4',
                                     'url': 'https://video.twimg.com/ext_tw_video/1054207338339397632/pu/vid/320x180/ooh1-gT_u0VhEqD0.mp4?tag=5'},
                                    {'content_type': 'application/x-mpegURL',
                                     'url': 'https://video.twimg.com/ext_tw_video/1054207338339397632/pu/pl/jKRdHm0Oj4VdiiRn.m3u8?tag=5'},
                                    {'bitrate': 2176000, 'content_type': 'video/mp4',
                                     'url': 'https://video.twimg.com/ext_tw_video/1054207338339397632/pu/vid/1280x720/UwEUZ08Afpnk5JGg.mp4?tag=5'}]},
                                'additional_media_info': {'monetizable': False}}]},
                           'metadata': {'result_type': 'popular', 'iso_language_code': 'en'},
                           'source': '<a href="http://twitter.com" rel="nofollow">Twitter Web Client</a>',
                           'in_reply_to_status_id': None, 'in_reply_to_status_id_str': None,
                           'in_reply_to_user_id': None, 'in_reply_to_user_id_str': None,
                           'in_reply_to_screen_name': None,
                           'user': {'id': 33583496, 'id_str': '33583496', 'name': 'Kansas City Chiefs',
                                    'screen_name': 'Chiefs', 'location': '#ChiefsKingdom',
                                    'description': 'Official Twitter account of the Kansas City #Chiefs.',
                                    'url': 'https://t.co/K7Q25DNqzQ', 'entities': {'url': {'urls': [
                                   {'url': 'https://t.co/K7Q25DNqzQ', 'expanded_url': 'https://www.chiefs.com',
                                    'display_url': 'chiefs.com', 'indices': [0, 23]}]}, 'description': {'urls': []}},
                                    'protected': False, 'followers_count': 1177354, 'friends_count': 296,
                                    'listed_count': 6042, 'created_at': 'Mon Apr 20 17:09:07 +0000 2009',
                                    'favourites_count': 5181, 'utc_offset': None, 'time_zone': None,
                                    'geo_enabled': True, 'verified': True, 'statuses_count': 36511, 'lang': 'en',
                                    'contributors_enabled': False, 'is_translator': False,
                                    'is_translation_enabled': False, 'profile_background_color': 'FFFFFF',
                                    'profile_background_image_url': 'http://abs.twimg.com/images/themes/theme1/bg.png',
                                    'profile_background_image_url_https': 'https://abs.twimg.com/images/themes/theme1/bg.png',
                                    'profile_background_tile': False,
                                    'profile_image_url': 'http://pbs.twimg.com/profile_images/1052598717566472192/uJ5pfeFM_normal.jpg',
                                    'profile_image_url_https': 'https://pbs.twimg.com/profile_images/1052598717566472192/uJ5pfeFM_normal.jpg',
                                    'profile_banner_url': 'https://pbs.twimg.com/profile_banners/33583496/1539794086',
                                    'profile_link_color': 'E31837', 'profile_sidebar_border_color': 'FFFFFF',
                                    'profile_sidebar_fill_color': 'F7FF0F', 'profile_text_color': '333333',
                                    'profile_use_background_image': False, 'has_extended_profile': False,
                                    'default_profile': False, 'default_profile_image': False, 'following': False,
                                    'follow_request_sent': False, 'notifications': False, 'translator_type': 'none'},
                           'geo': None, 'coordinates': None, 'place': None, 'contributors': None,
                           'is_quote_status': False, 'retweet_count': 646, 'favorite_count': 3110, 'favorited': False,
                           'retweeted': False, 'possibly_sensitive': False, 'lang': 'en'}, 'retweet_count': 19,
         'favorite_count': 129, 'favorited': False, 'retweeted': False, 'possibly_sensitive': False, 'lang': 'en'},
        {'created_at': 'Sun Oct 21 23:47:31 +0000 2018', 'id': 1054157264175677441, 'id_str': '1054157264175677441',
         'text': 'Tyreek Hill has scored eight TDs of 75+ yards, tying DeSean Jackson for the most among active @NFL players. Hill ha… https://t.co/gEUpK0U4pN',
         'truncated': True, 'entities': {'hashtags': [], 'symbols': [], 'user_mentions': [
            {'screen_name': 'NFL', 'name': 'NFL', 'id': 19426551, 'id_str': '19426551', 'indices': [94, 98]}], 'urls': [
            {'url': 'https://t.co/gEUpK0U4pN', 'expanded_url': 'https://twitter.com/i/web/status/1054157264175677441',
             'display_url': 'twitter.com/i/web/status/1…', 'indices': [117, 140]}]},
         'metadata': {'result_type': 'popular', 'iso_language_code': 'en'},
         'source': '<a href="https://about.twitter.com/products/tweetdeck" rel="nofollow">TweetDeck</a>',
         'in_reply_to_status_id': None, 'in_reply_to_status_id_str': None, 'in_reply_to_user_id': None,
         'in_reply_to_user_id_str': None, 'in_reply_to_screen_name': None,
         'user': {'id': 117640526, 'id_str': '117640526', 'name': 'Elias Sports Bureau', 'screen_name': 'EliasSports',
                  'location': 'New York, NY', 'description': '"If it ain\'t Elias, it ain\'t official."',
                  'url': 'http://t.co/XyRydQBIxG', 'entities': {'url': {'urls': [
                 {'url': 'http://t.co/XyRydQBIxG', 'expanded_url': 'http://www.elias.com', 'display_url': 'elias.com',
                  'indices': [0, 22]}]}, 'description': {'urls': []}}, 'protected': False, 'followers_count': 149308,
                  'friends_count': 0, 'listed_count': 2606, 'created_at': 'Fri Feb 26 04:23:00 +0000 2010',
                  'favourites_count': 24, 'utc_offset': None, 'time_zone': None, 'geo_enabled': False, 'verified': True,
                  'statuses_count': 12190, 'lang': 'en', 'contributors_enabled': False, 'is_translator': False,
                  'is_translation_enabled': False, 'profile_background_color': '000000',
                  'profile_background_image_url': 'http://abs.twimg.com/images/themes/theme1/bg.png',
                  'profile_background_image_url_https': 'https://abs.twimg.com/images/themes/theme1/bg.png',
                  'profile_background_tile': False,
                  'profile_image_url': 'http://pbs.twimg.com/profile_images/417012335807455234/J9AHpNph_normal.png',
                  'profile_image_url_https': 'https://pbs.twimg.com/profile_images/417012335807455234/J9AHpNph_normal.png',
                  'profile_banner_url': 'https://pbs.twimg.com/profile_banners/117640526/1360158373',
                  'profile_link_color': '0084B4', 'profile_sidebar_border_color': '000000',
                  'profile_sidebar_fill_color': 'DDEEF6', 'profile_text_color': '333333',
                  'profile_use_background_image': True, 'has_extended_profile': False, 'default_profile': False,
                  'default_profile_image': False, 'following': False, 'follow_request_sent': False,
                  'notifications': False, 'translator_type': 'none'}, 'geo': None, 'coordinates': None, 'place': None,
         'contributors': None, 'is_quote_status': False, 'retweet_count': 23, 'favorite_count': 55, 'favorited': False,
         'retweeted': False, 'lang': 'en'},
        {'created_at': 'Mon Oct 22 03:27:39 +0000 2018', 'id': 1054212662949830656, 'id_str': '1054212662949830656',
         'text': 'FINAL: Chiefs 45, Bengals 10. The Chiefs sit atop the AFC standings at 6-1. Patrick Mahomes threw 4 touchdowns. Kar… https://t.co/WGs09pPGen',
         'truncated': True, 'entities': {'hashtags': [], 'symbols': [], 'user_mentions': [], 'urls': [
            {'url': 'https://t.co/WGs09pPGen', 'expanded_url': 'https://twitter.com/i/web/status/1054212662949830656',
             'display_url': 'twitter.com/i/web/status/1…', 'indices': [117, 140]}]},
         'metadata': {'result_type': 'popular', 'iso_language_code': 'en'},
         'source': '<a href="https://about.twitter.com/products/tweetdeck" rel="nofollow">TweetDeck</a>',
         'in_reply_to_status_id': None, 'in_reply_to_status_id_str': None, 'in_reply_to_user_id': None,
         'in_reply_to_user_id_str': None, 'in_reply_to_screen_name': None,
         'user': {'id': 44722598, 'id_str': '44722598', 'name': 'Nate Taylor', 'screen_name': 'ByNateTaylor',
                  'location': 'Kansas City, MO',
                  'description': "Chiefs beat writer @TheAthleticKC (https://t.co/Nc74S9Oeb7). Husband to the lovely @hollym_taylor. Hayden's father. KC is home & Jesus is enough.",
                  'url': 'https://t.co/qNTEUyxwsL', 'entities': {'url': {'urls': [
                 {'url': 'https://t.co/qNTEUyxwsL', 'expanded_url': 'http://theathletic.com/team/chiefs',
                  'display_url': 'theathletic.com/team/chiefs', 'indices': [0, 23]}]}, 'description': {'urls': [
                 {'url': 'https://t.co/Nc74S9Oeb7', 'expanded_url': 'http://theathletic.com/freetrial',
                  'display_url': 'theathletic.com/freetrial', 'indices': [35, 58]}]}}, 'protected': False,
                  'followers_count': 13963, 'friends_count': 1118, 'listed_count': 666,
                  'created_at': 'Thu Jun 04 21:06:11 +0000 2009', 'favourites_count': 1346, 'utc_offset': None,
                  'time_zone': None, 'geo_enabled': True, 'verified': True, 'statuses_count': 21941, 'lang': 'en',
                  'contributors_enabled': False, 'is_translator': False, 'is_translation_enabled': False,
                  'profile_background_color': '89C9FA',
                  'profile_background_image_url': 'http://abs.twimg.com/images/themes/theme1/bg.png',
                  'profile_background_image_url_https': 'https://abs.twimg.com/images/themes/theme1/bg.png',
                  'profile_background_tile': False,
                  'profile_image_url': 'http://pbs.twimg.com/profile_images/1029120687343108096/s61w62LZ_normal.jpg',
                  'profile_image_url_https': 'https://pbs.twimg.com/profile_images/1029120687343108096/s61w62LZ_normal.jpg',
                  'profile_banner_url': 'https://pbs.twimg.com/profile_banners/44722598/1532109195',
                  'profile_link_color': 'E81C4F', 'profile_sidebar_border_color': '000000',
                  'profile_sidebar_fill_color': '000000', 'profile_text_color': '000000',
                  'profile_use_background_image': False, 'has_extended_profile': True, 'default_profile': False,
                  'default_profile_image': False, 'following': False, 'follow_request_sent': False,
                  'notifications': False, 'translator_type': 'none'}, 'geo': None, 'coordinates': None, 'place': None,
         'contributors': None, 'is_quote_status': False, 'retweet_count': 17, 'favorite_count': 172, 'favorited': False,
         'retweeted': False, 'lang': 'en'},
        {'created_at': 'Mon Oct 22 02:55:26 +0000 2018', 'id': 1054204555309801472, 'id_str': '1054204555309801472',
         'text': 'Career games with 4+ TD passes\nAlex Smith - 4\nPatrick Mahomes - 3\n\nTyreek Hill just dropped the pass that would hav… https://t.co/hR2vdy6Yzq',
         'truncated': True, 'entities': {'hashtags': [], 'symbols': [], 'user_mentions': [], 'urls': [
            {'url': 'https://t.co/hR2vdy6Yzq', 'expanded_url': 'https://twitter.com/i/web/status/1054204555309801472',
             'display_url': 'twitter.com/i/web/status/1…', 'indices': [117, 140]}]},
         'metadata': {'result_type': 'popular', 'iso_language_code': 'en'},
         'source': '<a href="http://twitter.com" rel="nofollow">Twitter Web Client</a>', 'in_reply_to_status_id': None,
         'in_reply_to_status_id_str': None, 'in_reply_to_user_id': None, 'in_reply_to_user_id_str': None,
         'in_reply_to_screen_name': None,
         'user': {'id': 343237375, 'id_str': '343237375', 'name': 'Scott Kacsmar', 'screen_name': 'FO_ScottKacsmar',
                  'location': 'Pittsburgh, PA',
                  'description': 'NFL writer. Football Outsiders Assistant Editor. PFWA. Film buff/future screenwriter. 4QC/GWD/ALEX creator. Eating up the scum is the hardest thing for me to do',
                  'url': 'https://t.co/YrVbHaYvI6', 'entities': {'url': {'urls': [
                 {'url': 'https://t.co/YrVbHaYvI6', 'expanded_url': 'http://captaincomeback.wordpress.com/',
                  'display_url': 'captaincomeback.wordpress.com', 'indices': [0, 23]}]}, 'description': {'urls': []}},
                  'protected': False, 'followers_count': 20529, 'friends_count': 975, 'listed_count': 1148,
                  'created_at': 'Wed Jul 27 07:53:41 +0000 2011', 'favourites_count': 2725, 'utc_offset': None,
                  'time_zone': None, 'geo_enabled': True, 'verified': True, 'statuses_count': 132373, 'lang': 'en',
                  'contributors_enabled': False, 'is_translator': False, 'is_translation_enabled': False,
                  'profile_background_color': '1A171A',
                  'profile_background_image_url': 'http://abs.twimg.com/images/themes/theme15/bg.png',
                  'profile_background_image_url_https': 'https://abs.twimg.com/images/themes/theme15/bg.png',
                  'profile_background_tile': True,
                  'profile_image_url': 'http://pbs.twimg.com/profile_images/2173521321/belly2__2__normal.jpg',
                  'profile_image_url_https': 'https://pbs.twimg.com/profile_images/2173521321/belly2__2__normal.jpg',
                  'profile_banner_url': 'https://pbs.twimg.com/profile_banners/343237375/1436001237',
                  'profile_link_color': '1937CC', 'profile_sidebar_border_color': 'FFFFFF',
                  'profile_sidebar_fill_color': '000000', 'profile_text_color': '000000',
                  'profile_use_background_image': True, 'has_extended_profile': True, 'default_profile': False,
                  'default_profile_image': False, 'following': False, 'follow_request_sent': False,
                  'notifications': False, 'translator_type': 'none'}, 'geo': None, 'coordinates': None, 'place': None,
         'contributors': None, 'is_quote_status': False, 'retweet_count': 25, 'favorite_count': 84, 'favorited': False,
         'retweeted': False, 'lang': 'en'},
        {'created_at': 'Wed Oct 17 10:43:13 +0000 2018', 'id': 1052510337436700672, 'id_str': '1052510337436700672',
         'text': 'Absolutely insane to me that Tyreek Hill, who only got probation for beating and strangling his pregnant girlfriend… https://t.co/2XYXUkhL07',
         'truncated': True, 'entities': {'hashtags': [], 'symbols': [], 'user_mentions': [], 'urls': [
            {'url': 'https://t.co/2XYXUkhL07', 'expanded_url': 'https://twitter.com/i/web/status/1052510337436700672',
             'display_url': 'twitter.com/i/web/status/1…', 'indices': [117, 140]}]},
         'metadata': {'result_type': 'popular', 'iso_language_code': 'en'},
         'source': '<a href="http://twitter.com/download/iphone" rel="nofollow">Twitter for iPhone</a>',
         'in_reply_to_status_id': None, 'in_reply_to_status_id_str': None, 'in_reply_to_user_id': None,
         'in_reply_to_user_id_str': None, 'in_reply_to_screen_name': None,
         'user': {'id': 50772918, 'id_str': '50772918', 'name': 'Clay Travis', 'screen_name': 'ClayTravis',
                  'location': 'Nashville',
                  'description': 'https://t.co/Ut3ejMNAQd, @outkick @foxsportsradio 6-9 am et & @lockitinonfs1 TV show 4:30 et, author, Republicans Buy Sneakers Too, dad of three boys, lawyer',
                  'url': 'https://t.co/c46ZljJT0b', 'entities': {'url': {'urls': [
                 {'url': 'https://t.co/c46ZljJT0b', 'expanded_url': 'http://www.outkick.com',
                  'display_url': 'outkick.com', 'indices': [0, 23]}]}, 'description': {'urls': [
                 {'url': 'https://t.co/Ut3ejMNAQd', 'expanded_url': 'http://Outkick.com', 'display_url': 'Outkick.com',
                  'indices': [0, 23]}]}}, 'protected': False, 'followers_count': 605190, 'friends_count': 313,
                  'listed_count': 3471, 'created_at': 'Thu Jun 25 21:16:40 +0000 2009', 'favourites_count': 441,
                  'utc_offset': None, 'time_zone': None, 'geo_enabled': False, 'verified': True,
                  'statuses_count': 90844, 'lang': 'en', 'contributors_enabled': False, 'is_translator': False,
                  'is_translation_enabled': False, 'profile_background_color': '9AE4E8',
                  'profile_background_image_url': 'http://abs.twimg.com/images/themes/theme1/bg.png',
                  'profile_background_image_url_https': 'https://abs.twimg.com/images/themes/theme1/bg.png',
                  'profile_background_tile': True,
                  'profile_image_url': 'http://pbs.twimg.com/profile_images/668983225860034564/PIdSf23G_normal.jpg',
                  'profile_image_url_https': 'https://pbs.twimg.com/profile_images/668983225860034564/PIdSf23G_normal.jpg',
                  'profile_banner_url': 'https://pbs.twimg.com/profile_banners/50772918/1448333179',
                  'profile_link_color': '0084B4', 'profile_sidebar_border_color': 'FFFFFF',
                  'profile_sidebar_fill_color': 'DDFFCC', 'profile_text_color': '333333',
                  'profile_use_background_image': True, 'has_extended_profile': False, 'default_profile': False,
                  'default_profile_image': False, 'following': False, 'follow_request_sent': False,
                  'notifications': False, 'translator_type': 'none'}, 'geo': None, 'coordinates': None, 'place': None,
         'contributors': None, 'is_quote_status': False, 'retweet_count': 3086, 'favorite_count': 14227,
         'favorited': False, 'retweeted': False, 'lang': 'en'}]
