data = [{'created_at': 'Mon Oct 22 10:28:06 +0000 2018', 'id': 1054318472547708928, 'id_str': '1054318472547708928',
         'text': '@YahooNoise @LizLoza_FF @andybehrens @Michael_Fabiano @adamrank @cfrelund @MatthewBerryTMR @FieldYates When you hav… https://t.co/FhXQCwAbGs',
         'truncated': True, 'entities': {'hashtags': [], 'symbols': [], 'user_mentions': [
        {'screen_name': 'YahooNoise', 'name': 'Brad Evans', 'id': 78105431, 'id_str': '78105431', 'indices': [0, 11]},
        {'screen_name': 'LizLoza_FF', 'name': 'Liz Loza', 'id': 80101877, 'id_str': '80101877', 'indices': [12, 23]},
        {'screen_name': 'andybehrens', 'name': 'Andy Behrens', 'id': 34767359, 'id_str': '34767359',
         'indices': [24, 36]},
        {'screen_name': 'Michael_Fabiano', 'name': 'Michael Fabiano', 'id': 37106040, 'id_str': '37106040',
         'indices': [37, 53]},
        {'screen_name': 'adamrank', 'name': 'Adam Rank', 'id': 44516935, 'id_str': '44516935', 'indices': [54, 63]},
        {'screen_name': 'cfrelund', 'name': 'cynthia frelund', 'id': 304593201, 'id_str': '304593201',
         'indices': [64, 73]},
        {'screen_name': 'MatthewBerryTMR', 'name': 'Matthew Berry', 'id': 20899023, 'id_str': '20899023',
         'indices': [74, 90]},
        {'screen_name': 'FieldYates', 'name': 'Field Yates', 'id': 58919137, 'id_str': '58919137',
         'indices': [91, 102]}], 'urls': [
        {'url': 'https://t.co/FhXQCwAbGs', 'expanded_url': 'https://twitter.com/i/web/status/1054318472547708928',
         'display_url': 'twitter.com/i/web/status/1…', 'indices': [117, 140]}]},
         'metadata': {'iso_language_code': 'en', 'result_type': 'recent'},
         'source': '<a href="http://twitter.com/download/iphone" rel="nofollow">Twitter for iPhone</a>',
         'in_reply_to_status_id': None, 'in_reply_to_status_id_str': None, 'in_reply_to_user_id': 78105431,
         'in_reply_to_user_id_str': '78105431', 'in_reply_to_screen_name': 'YahooNoise',
         'user': {'id': 218011593, 'id_str': '218011593', 'name': 'Adam Joseph Raper', 'screen_name': 'AdamJosephRaper',
                  'location': 'Lebanon, Ohio',
                  'description': 'GO COLTS! GO REDS! O-H-I-O! WHO-DEY! fantasy sports fanatic!', 'url': None,
                  'entities': {'description': {'urls': []}}, 'protected': False, 'followers_count': 62,
                  'friends_count': 654, 'listed_count': 0, 'created_at': 'Sun Nov 21 04:57:14 +0000 2010',
                  'favourites_count': 16, 'utc_offset': None, 'time_zone': None, 'geo_enabled': False,
                  'verified': False, 'statuses_count': 1767, 'lang': 'en', 'contributors_enabled': False,
                  'is_translator': False, 'is_translation_enabled': False, 'profile_background_color': 'C0DEED',
                  'profile_background_image_url': 'http://abs.twimg.com/images/themes/theme1/bg.png',
                  'profile_background_image_url_https': 'https://abs.twimg.com/images/themes/theme1/bg.png',
                  'profile_background_tile': False,
                  'profile_image_url': 'http://pbs.twimg.com/profile_images/924582807095169024/KMkIXRau_normal.jpg',
                  'profile_image_url_https': 'https://pbs.twimg.com/profile_images/924582807095169024/KMkIXRau_normal.jpg',
                  'profile_banner_url': 'https://pbs.twimg.com/profile_banners/218011593/1509272695',
                  'profile_link_color': '1DA1F2', 'profile_sidebar_border_color': 'C0DEED',
                  'profile_sidebar_fill_color': 'DDEEF6', 'profile_text_color': '333333',
                  'profile_use_background_image': True, 'has_extended_profile': False, 'default_profile': True,
                  'default_profile_image': False, 'following': False, 'follow_request_sent': False,
                  'notifications': False, 'translator_type': 'none'}, 'geo': None, 'coordinates': None, 'place': None,
         'contributors': None, 'is_quote_status': False, 'retweet_count': 0, 'favorite_count': 0, 'favorited': False,
         'retweeted': False, 'possibly_sensitive': False, 'lang': 'en'},
        {'created_at': 'Mon Oct 22 10:22:15 +0000 2018', 'id': 1054316999260692481, 'id_str': '1054316999260692481',
         'text': 'The @Chiefs are also saving #KC! @ArrowheadPride #ChiefsKingdom #Mahomes https://t.co/ek5KaGzUeb',
         'truncated': False, 'entities': {
            'hashtags': [{'text': 'KC', 'indices': [28, 31]}, {'text': 'ChiefsKingdom', 'indices': [49, 63]},
                         {'text': 'Mahomes', 'indices': [64, 72]}], 'symbols': [], 'user_mentions': [
                {'screen_name': 'Chiefs', 'name': 'Kansas City Chiefs', 'id': 33583496, 'id_str': '33583496',
                 'indices': [4, 11]},
                {'screen_name': 'ArrowheadPride', 'name': 'Arrowhead Pride', 'id': 24216003, 'id_str': '24216003',
                 'indices': [33, 48]}], 'urls': [{'url': 'https://t.co/ek5KaGzUeb',
                                                  'expanded_url': 'https://www.si.com/nfl/2018/10/21/chiefs-bengals-patrick-mahomes-kareem-hunt-tyreek-hill-sunday-night-football',
                                                  'display_url': 'si.com/nfl/2018/10/21…', 'indices': [73, 96]}]},
         'metadata': {'iso_language_code': 'en', 'result_type': 'recent'},
         'source': '<a href="http://twitter.com/download/iphone" rel="nofollow">Twitter for iPhone</a>',
         'in_reply_to_status_id': None, 'in_reply_to_status_id_str': None, 'in_reply_to_user_id': None,
         'in_reply_to_user_id_str': None, 'in_reply_to_screen_name': None,
         'user': {'id': 191234002, 'id_str': '191234002', 'name': 'Krista Klaus', 'screen_name': 'kristakcbiz',
                  'location': 'Kansas City',
                  'description': 'Media relations/PR consultant MetroWireMedia managing editor', 'url': None,
                  'entities': {'description': {'urls': []}}, 'protected': False, 'followers_count': 3213,
                  'friends_count': 2085, 'listed_count': 120, 'created_at': 'Wed Sep 15 23:00:53 +0000 2010',
                  'favourites_count': 2014, 'utc_offset': None, 'time_zone': None, 'geo_enabled': True,
                  'verified': False, 'statuses_count': 3790, 'lang': 'en', 'contributors_enabled': False,
                  'is_translator': False, 'is_translation_enabled': False, 'profile_background_color': 'C0DEED',
                  'profile_background_image_url': 'http://abs.twimg.com/images/themes/theme1/bg.png',
                  'profile_background_image_url_https': 'https://abs.twimg.com/images/themes/theme1/bg.png',
                  'profile_background_tile': False,
                  'profile_image_url': 'http://pbs.twimg.com/profile_images/624919853485305857/yunpwaSd_normal.jpg',
                  'profile_image_url_https': 'https://pbs.twimg.com/profile_images/624919853485305857/yunpwaSd_normal.jpg',
                  'profile_banner_url': 'https://pbs.twimg.com/profile_banners/191234002/1437827425',
                  'profile_link_color': '1DA1F2', 'profile_sidebar_border_color': 'C0DEED',
                  'profile_sidebar_fill_color': 'DDEEF6', 'profile_text_color': '333333',
                  'profile_use_background_image': True, 'has_extended_profile': False, 'default_profile': True,
                  'default_profile_image': False, 'following': False, 'follow_request_sent': False,
                  'notifications': False, 'translator_type': 'none'}, 'geo': None, 'coordinates': None, 'place': None,
         'contributors': None, 'is_quote_status': False, 'retweet_count': 0, 'favorite_count': 0, 'favorited': False,
         'retweeted': False, 'possibly_sensitive': False, 'lang': 'en'},
        {'created_at': 'Mon Oct 22 10:18:14 +0000 2018', 'id': 1054315986755567617, 'id_str': '1054315986755567617',
         'text': 'RT @mother_bag_shop: Tyreek Hill finally gets first TD of game\nhttps://t.co/CGTp7SiCNo https://t.co/NGZPsv4D7s',
         'truncated': False, 'entities': {'hashtags': [], 'symbols': [], 'user_mentions': [
            {'screen_name': 'mother_bag_shop', 'name': 'マザーバッグ専門ショップ', 'id': 3240339188, 'id_str': '3240339188',
             'indices': [3, 19]}], 'urls': [
            {'url': 'https://t.co/CGTp7SiCNo', 'expanded_url': 'http://rakushop.org/mother_bag/b/1444586/',
             'display_url': 'rakushop.org/mother_bag/b/1…', 'indices': [63, 86]}], 'media': [
            {'id': 1054313207358083073, 'id_str': '1054313207358083073', 'indices': [87, 110],
             'media_url': 'http://pbs.twimg.com/media/DqGsRq6U0AEpx3C.jpg',
             'media_url_https': 'https://pbs.twimg.com/media/DqGsRq6U0AEpx3C.jpg', 'url': 'https://t.co/NGZPsv4D7s',
             'display_url': 'pic.twitter.com/NGZPsv4D7s',
             'expanded_url': 'https://twitter.com/mother_bag_shop/status/1054313208586989568/photo/1', 'type': 'photo',
             'sizes': {'medium': {'w': 480, 'h': 360, 'resize': 'fit'}, 'thumb': {'w': 150, 'h': 150, 'resize': 'crop'},
                       'large': {'w': 480, 'h': 360, 'resize': 'fit'}, 'small': {'w': 480, 'h': 360, 'resize': 'fit'}},
             'source_status_id': 1054313208586989568, 'source_status_id_str': '1054313208586989568',
             'source_user_id': 3240339188, 'source_user_id_str': '3240339188'}]}, 'extended_entities': {'media': [
            {'id': 1054313207358083073, 'id_str': '1054313207358083073', 'indices': [87, 110],
             'media_url': 'http://pbs.twimg.com/media/DqGsRq6U0AEpx3C.jpg',
             'media_url_https': 'https://pbs.twimg.com/media/DqGsRq6U0AEpx3C.jpg', 'url': 'https://t.co/NGZPsv4D7s',
             'display_url': 'pic.twitter.com/NGZPsv4D7s',
             'expanded_url': 'https://twitter.com/mother_bag_shop/status/1054313208586989568/photo/1', 'type': 'photo',
             'sizes': {'medium': {'w': 480, 'h': 360, 'resize': 'fit'}, 'thumb': {'w': 150, 'h': 150, 'resize': 'crop'},
                       'large': {'w': 480, 'h': 360, 'resize': 'fit'}, 'small': {'w': 480, 'h': 360, 'resize': 'fit'}},
             'source_status_id': 1054313208586989568, 'source_status_id_str': '1054313208586989568',
             'source_user_id': 3240339188, 'source_user_id_str': '3240339188'}]},
         'metadata': {'iso_language_code': 'en', 'result_type': 'recent'},
         'source': '<a href="http://twitter.com/download/iphone" rel="nofollow">Twitter for iPhone</a>',
         'in_reply_to_status_id': None, 'in_reply_to_status_id_str': None, 'in_reply_to_user_id': None,
         'in_reply_to_user_id_str': None, 'in_reply_to_screen_name': None,
         'user': {'id': 1013161819999883264, 'id_str': '1013161819999883264', 'name': 'べいまる⭐️(RT垢)',
                  'screen_name': '6BZxZZUNQZe7FQF', 'location': '日本',
                  'description': 'ちゃん様とお呼び！ TL荒らします鬱陶しいと思われたならミュートかブロックしてください RTといいねだけしますので会話は挨拶程度でご遠慮お願い致します dmも返信は期待しないでください',
                  'url': None, 'entities': {'description': {'urls': []}}, 'protected': False, 'followers_count': 1761,
                  'friends_count': 1780, 'listed_count': 14, 'created_at': 'Sat Jun 30 20:46:16 +0000 2018',
                  'favourites_count': 10928, 'utc_offset': None, 'time_zone': None, 'geo_enabled': False,
                  'verified': False, 'statuses_count': 7055, 'lang': 'ja', 'contributors_enabled': False,
                  'is_translator': False, 'is_translation_enabled': False, 'profile_background_color': 'F5F8FA',
                  'profile_background_image_url': None, 'profile_background_image_url_https': None,
                  'profile_background_tile': False,
                  'profile_image_url': 'http://pbs.twimg.com/profile_images/1046171150735138816/9yRnXjsY_normal.jpg',
                  'profile_image_url_https': 'https://pbs.twimg.com/profile_images/1046171150735138816/9yRnXjsY_normal.jpg',
                  'profile_banner_url': 'https://pbs.twimg.com/profile_banners/1013161819999883264/1537360031',
                  'profile_link_color': '1DA1F2', 'profile_sidebar_border_color': 'C0DEED',
                  'profile_sidebar_fill_color': 'DDEEF6', 'profile_text_color': '333333',
                  'profile_use_background_image': True, 'has_extended_profile': False, 'default_profile': True,
                  'default_profile_image': False, 'following': False, 'follow_request_sent': False,
                  'notifications': False, 'translator_type': 'none'}, 'geo': None, 'coordinates': None, 'place': None,
         'contributors': None,
         'retweeted_status': {'created_at': 'Mon Oct 22 10:07:11 +0000 2018', 'id': 1054313208586989568,
                              'id_str': '1054313208586989568',
                              'text': 'Tyreek Hill finally gets first TD of game\nhttps://t.co/CGTp7SiCNo https://t.co/NGZPsv4D7s',
                              'truncated': False, 'entities': {'hashtags': [], 'symbols': [], 'user_mentions': [],
                                                               'urls': [{'url': 'https://t.co/CGTp7SiCNo',
                                                                         'expanded_url': 'http://rakushop.org/mother_bag/b/1444586/',
                                                                         'display_url': 'rakushop.org/mother_bag/b/1…',
                                                                         'indices': [42, 65]}], 'media': [
                     {'id': 1054313207358083073, 'id_str': '1054313207358083073', 'indices': [66, 89],
                      'media_url': 'http://pbs.twimg.com/media/DqGsRq6U0AEpx3C.jpg',
                      'media_url_https': 'https://pbs.twimg.com/media/DqGsRq6U0AEpx3C.jpg',
                      'url': 'https://t.co/NGZPsv4D7s', 'display_url': 'pic.twitter.com/NGZPsv4D7s',
                      'expanded_url': 'https://twitter.com/mother_bag_shop/status/1054313208586989568/photo/1',
                      'type': 'photo', 'sizes': {'medium': {'w': 480, 'h': 360, 'resize': 'fit'},
                                                 'thumb': {'w': 150, 'h': 150, 'resize': 'crop'},
                                                 'large': {'w': 480, 'h': 360, 'resize': 'fit'},
                                                 'small': {'w': 480, 'h': 360, 'resize': 'fit'}}}]},
                              'extended_entities': {'media': [
                                  {'id': 1054313207358083073, 'id_str': '1054313207358083073', 'indices': [66, 89],
                                   'media_url': 'http://pbs.twimg.com/media/DqGsRq6U0AEpx3C.jpg',
                                   'media_url_https': 'https://pbs.twimg.com/media/DqGsRq6U0AEpx3C.jpg',
                                   'url': 'https://t.co/NGZPsv4D7s', 'display_url': 'pic.twitter.com/NGZPsv4D7s',
                                   'expanded_url': 'https://twitter.com/mother_bag_shop/status/1054313208586989568/photo/1',
                                   'type': 'photo', 'sizes': {'medium': {'w': 480, 'h': 360, 'resize': 'fit'},
                                                              'thumb': {'w': 150, 'h': 150, 'resize': 'crop'},
                                                              'large': {'w': 480, 'h': 360, 'resize': 'fit'},
                                                              'small': {'w': 480, 'h': 360, 'resize': 'fit'}}}]},
                              'metadata': {'iso_language_code': 'en', 'result_type': 'recent'},
                              'source': '<a href="http://rakushop.org/mother_bag/" rel="nofollow">mother_bag tweeter2</a>',
                              'in_reply_to_status_id': None, 'in_reply_to_status_id_str': None,
                              'in_reply_to_user_id': None, 'in_reply_to_user_id_str': None,
                              'in_reply_to_screen_name': None,
                              'user': {'id': 3240339188, 'id_str': '3240339188', 'name': 'マザーバッグ専門ショップ',
                                       'screen_name': 'mother_bag_shop', 'location': '', 'description': '', 'url': None,
                                       'entities': {'description': {'urls': []}}, 'protected': False,
                                       'followers_count': 8274, 'friends_count': 8843, 'listed_count': 8,
                                       'created_at': 'Tue Jun 09 02:05:06 +0000 2015', 'favourites_count': 0,
                                       'utc_offset': None, 'time_zone': None, 'geo_enabled': False, 'verified': False,
                                       'statuses_count': 9837, 'lang': 'ja', 'contributors_enabled': False,
                                       'is_translator': False, 'is_translation_enabled': False,
                                       'profile_background_color': 'C0DEED',
                                       'profile_background_image_url': 'http://abs.twimg.com/images/themes/theme1/bg.png',
                                       'profile_background_image_url_https': 'https://abs.twimg.com/images/themes/theme1/bg.png',
                                       'profile_background_tile': False,
                                       'profile_image_url': 'http://pbs.twimg.com/profile_images/608092550382026752/yPLkBKJa_normal.jpg',
                                       'profile_image_url_https': 'https://pbs.twimg.com/profile_images/608092550382026752/yPLkBKJa_normal.jpg',
                                       'profile_link_color': '1DA1F2', 'profile_sidebar_border_color': 'C0DEED',
                                       'profile_sidebar_fill_color': 'DDEEF6', 'profile_text_color': '333333',
                                       'profile_use_background_image': True, 'has_extended_profile': False,
                                       'default_profile': True, 'default_profile_image': False, 'following': False,
                                       'follow_request_sent': False, 'notifications': False, 'translator_type': 'none'},
                              'geo': None, 'coordinates': None, 'place': None, 'contributors': None,
                              'is_quote_status': False, 'retweet_count': 1, 'favorite_count': 2, 'favorited': False,
                              'retweeted': False, 'possibly_sensitive': False, 'lang': 'en'}, 'is_quote_status': False,
         'retweet_count': 1, 'favorite_count': 0, 'favorited': False, 'retweeted': False, 'possibly_sensitive': True,
         'lang': 'en'},
        {'created_at': 'Mon Oct 22 10:07:11 +0000 2018', 'id': 1054313208586989568, 'id_str': '1054313208586989568',
         'text': 'Tyreek Hill finally gets first TD of game\nhttps://t.co/CGTp7SiCNo https://t.co/NGZPsv4D7s',
         'truncated': False, 'entities': {'hashtags': [], 'symbols': [], 'user_mentions': [], 'urls': [
            {'url': 'https://t.co/CGTp7SiCNo', 'expanded_url': 'http://rakushop.org/mother_bag/b/1444586/',
             'display_url': 'rakushop.org/mother_bag/b/1…', 'indices': [42, 65]}], 'media': [
            {'id': 1054313207358083073, 'id_str': '1054313207358083073', 'indices': [66, 89],
             'media_url': 'http://pbs.twimg.com/media/DqGsRq6U0AEpx3C.jpg',
             'media_url_https': 'https://pbs.twimg.com/media/DqGsRq6U0AEpx3C.jpg', 'url': 'https://t.co/NGZPsv4D7s',
             'display_url': 'pic.twitter.com/NGZPsv4D7s',
             'expanded_url': 'https://twitter.com/mother_bag_shop/status/1054313208586989568/photo/1', 'type': 'photo',
             'sizes': {'medium': {'w': 480, 'h': 360, 'resize': 'fit'}, 'thumb': {'w': 150, 'h': 150, 'resize': 'crop'},
                       'large': {'w': 480, 'h': 360, 'resize': 'fit'},
                       'small': {'w': 480, 'h': 360, 'resize': 'fit'}}}]}, 'extended_entities': {'media': [
            {'id': 1054313207358083073, 'id_str': '1054313207358083073', 'indices': [66, 89],
             'media_url': 'http://pbs.twimg.com/media/DqGsRq6U0AEpx3C.jpg',
             'media_url_https': 'https://pbs.twimg.com/media/DqGsRq6U0AEpx3C.jpg', 'url': 'https://t.co/NGZPsv4D7s',
             'display_url': 'pic.twitter.com/NGZPsv4D7s',
             'expanded_url': 'https://twitter.com/mother_bag_shop/status/1054313208586989568/photo/1', 'type': 'photo',
             'sizes': {'medium': {'w': 480, 'h': 360, 'resize': 'fit'}, 'thumb': {'w': 150, 'h': 150, 'resize': 'crop'},
                       'large': {'w': 480, 'h': 360, 'resize': 'fit'},
                       'small': {'w': 480, 'h': 360, 'resize': 'fit'}}}]},
         'metadata': {'iso_language_code': 'en', 'result_type': 'recent'},
         'source': '<a href="http://rakushop.org/mother_bag/" rel="nofollow">mother_bag tweeter2</a>',
         'in_reply_to_status_id': None, 'in_reply_to_status_id_str': None, 'in_reply_to_user_id': None,
         'in_reply_to_user_id_str': None, 'in_reply_to_screen_name': None,
         'user': {'id': 3240339188, 'id_str': '3240339188', 'name': 'マザーバッグ専門ショップ', 'screen_name': 'mother_bag_shop',
                  'location': '', 'description': '', 'url': None, 'entities': {'description': {'urls': []}},
                  'protected': False, 'followers_count': 8274, 'friends_count': 8843, 'listed_count': 8,
                  'created_at': 'Tue Jun 09 02:05:06 +0000 2015', 'favourites_count': 0, 'utc_offset': None,
                  'time_zone': None, 'geo_enabled': False, 'verified': False, 'statuses_count': 9837, 'lang': 'ja',
                  'contributors_enabled': False, 'is_translator': False, 'is_translation_enabled': False,
                  'profile_background_color': 'C0DEED',
                  'profile_background_image_url': 'http://abs.twimg.com/images/themes/theme1/bg.png',
                  'profile_background_image_url_https': 'https://abs.twimg.com/images/themes/theme1/bg.png',
                  'profile_background_tile': False,
                  'profile_image_url': 'http://pbs.twimg.com/profile_images/608092550382026752/yPLkBKJa_normal.jpg',
                  'profile_image_url_https': 'https://pbs.twimg.com/profile_images/608092550382026752/yPLkBKJa_normal.jpg',
                  'profile_link_color': '1DA1F2', 'profile_sidebar_border_color': 'C0DEED',
                  'profile_sidebar_fill_color': 'DDEEF6', 'profile_text_color': '333333',
                  'profile_use_background_image': True, 'has_extended_profile': False, 'default_profile': True,
                  'default_profile_image': False, 'following': False, 'follow_request_sent': False,
                  'notifications': False, 'translator_type': 'none'}, 'geo': None, 'coordinates': None, 'place': None,
         'contributors': None, 'is_quote_status': False, 'retweet_count': 1, 'favorite_count': 2, 'favorited': False,
         'retweeted': False, 'possibly_sensitive': False, 'lang': 'en'},
        {'created_at': 'Mon Oct 22 10:06:26 +0000 2018', 'id': 1054313020749373440, 'id_str': '1054313020749373440',
         'text': 'Chiefs fans comforts Tyreek Hill after dropped TD\nhttps://t.co/7KPSaBrOom https://t.co/yBTUSoNxHc',
         'truncated': False, 'entities': {'hashtags': [], 'symbols': [], 'user_mentions': [], 'urls': [
            {'url': 'https://t.co/7KPSaBrOom', 'expanded_url': 'http://shopblogs.net/sandal/b/1610741/',
             'display_url': 'shopblogs.net/sandal/b/16107…', 'indices': [50, 73]}], 'media': [
            {'id': 1054313019449077760, 'id_str': '1054313019449077760', 'indices': [74, 97],
             'media_url': 'http://pbs.twimg.com/media/DqGsGu5U8AA6aeD.jpg',
             'media_url_https': 'https://pbs.twimg.com/media/DqGsGu5U8AA6aeD.jpg', 'url': 'https://t.co/yBTUSoNxHc',
             'display_url': 'pic.twitter.com/yBTUSoNxHc',
             'expanded_url': 'https://twitter.com/mania_sandal/status/1054313020749373440/photo/1', 'type': 'photo',
             'sizes': {'thumb': {'w': 150, 'h': 150, 'resize': 'crop'}, 'small': {'w': 480, 'h': 360, 'resize': 'fit'},
                       'medium': {'w': 480, 'h': 360, 'resize': 'fit'},
                       'large': {'w': 480, 'h': 360, 'resize': 'fit'}}}]}, 'extended_entities': {'media': [
            {'id': 1054313019449077760, 'id_str': '1054313019449077760', 'indices': [74, 97],
             'media_url': 'http://pbs.twimg.com/media/DqGsGu5U8AA6aeD.jpg',
             'media_url_https': 'https://pbs.twimg.com/media/DqGsGu5U8AA6aeD.jpg', 'url': 'https://t.co/yBTUSoNxHc',
             'display_url': 'pic.twitter.com/yBTUSoNxHc',
             'expanded_url': 'https://twitter.com/mania_sandal/status/1054313020749373440/photo/1', 'type': 'photo',
             'sizes': {'thumb': {'w': 150, 'h': 150, 'resize': 'crop'}, 'small': {'w': 480, 'h': 360, 'resize': 'fit'},
                       'medium': {'w': 480, 'h': 360, 'resize': 'fit'},
                       'large': {'w': 480, 'h': 360, 'resize': 'fit'}}}]},
         'metadata': {'iso_language_code': 'en', 'result_type': 'recent'},
         'source': '<a href="http://shopblogs.net/sandal/" rel="nofollow">sandal tweeter</a>',
         'in_reply_to_status_id': None, 'in_reply_to_status_id_str': None, 'in_reply_to_user_id': None,
         'in_reply_to_user_id_str': None, 'in_reply_to_screen_name': None,
         'user': {'id': 2915934199, 'id_str': '2915934199', 'name': 'サンダル専門店 サンダルMANIA', 'screen_name': 'mania_sandal',
                  'location': '', 'description': 'サンダルの通販専用ショップです。各種ブランドや健康・Tatamiサンダルなど！',
                  'url': 'http://t.co/K1e99tmc1v', 'entities': {'url': {'urls': [
                 {'url': 'http://t.co/K1e99tmc1v', 'expanded_url': 'http://shopblogs.net/sandal/',
                  'display_url': 'shopblogs.net/sandal/', 'indices': [0, 22]}]}, 'description': {'urls': []}},
                  'protected': False, 'followers_count': 7451, 'friends_count': 7695, 'listed_count': 4,
                  'created_at': 'Mon Dec 01 19:29:43 +0000 2014', 'favourites_count': 0, 'utc_offset': None,
                  'time_zone': None, 'geo_enabled': False, 'verified': False, 'statuses_count': 11730, 'lang': 'ja',
                  'contributors_enabled': False, 'is_translator': False, 'is_translation_enabled': False,
                  'profile_background_color': '000000',
                  'profile_background_image_url': 'http://abs.twimg.com/images/themes/theme1/bg.png',
                  'profile_background_image_url_https': 'https://abs.twimg.com/images/themes/theme1/bg.png',
                  'profile_background_tile': False,
                  'profile_image_url': 'http://pbs.twimg.com/profile_images/539501871291834369/Zdp-4Nna_normal.jpeg',
                  'profile_image_url_https': 'https://pbs.twimg.com/profile_images/539501871291834369/Zdp-4Nna_normal.jpeg',
                  'profile_link_color': '520029', 'profile_sidebar_border_color': '000000',
                  'profile_sidebar_fill_color': '000000', 'profile_text_color': '000000',
                  'profile_use_background_image': False, 'has_extended_profile': False, 'default_profile': False,
                  'default_profile_image': False, 'following': False, 'follow_request_sent': False,
                  'notifications': False, 'translator_type': 'none'}, 'geo': None, 'coordinates': None, 'place': None,
         'contributors': None, 'is_quote_status': False, 'retweet_count': 0, 'favorite_count': 0, 'favorited': False,
         'retweeted': False, 'possibly_sensitive': False, 'lang': 'en'},
        {'created_at': 'Mon Oct 22 10:01:27 +0000 2018', 'id': 1054311764685254656, 'id_str': '1054311764685254656',
         'text': 'Tyreek Hill CPR TD celebration: Bengals vs Chiefs Week 7\nhttps://t.co/pxqO59Lwii https://t.co/GwnbGQqHtr',
         'truncated': False, 'entities': {'hashtags': [], 'symbols': [], 'user_mentions': [], 'urls': [
            {'url': 'https://t.co/pxqO59Lwii', 'expanded_url': 'http://shopblogs.net/blouse_king/b/1610733/',
             'display_url': 'shopblogs.net/blouse_king/b/…', 'indices': [57, 80]}], 'media': [
            {'id': 1054311762990747648, 'id_str': '1054311762990747648', 'indices': [81, 104],
             'media_url': 'http://pbs.twimg.com/media/DqGq9mOUUAAxqYM.jpg',
             'media_url_https': 'https://pbs.twimg.com/media/DqGq9mOUUAAxqYM.jpg', 'url': 'https://t.co/GwnbGQqHtr',
             'display_url': 'pic.twitter.com/GwnbGQqHtr',
             'expanded_url': 'https://twitter.com/blouse_king/status/1054311764685254656/photo/1', 'type': 'photo',
             'sizes': {'small': {'w': 480, 'h': 360, 'resize': 'fit'}, 'thumb': {'w': 150, 'h': 150, 'resize': 'crop'},
                       'large': {'w': 480, 'h': 360, 'resize': 'fit'},
                       'medium': {'w': 480, 'h': 360, 'resize': 'fit'}}}]}, 'extended_entities': {'media': [
            {'id': 1054311762990747648, 'id_str': '1054311762990747648', 'indices': [81, 104],
             'media_url': 'http://pbs.twimg.com/media/DqGq9mOUUAAxqYM.jpg',
             'media_url_https': 'https://pbs.twimg.com/media/DqGq9mOUUAAxqYM.jpg', 'url': 'https://t.co/GwnbGQqHtr',
             'display_url': 'pic.twitter.com/GwnbGQqHtr',
             'expanded_url': 'https://twitter.com/blouse_king/status/1054311764685254656/photo/1', 'type': 'photo',
             'sizes': {'small': {'w': 480, 'h': 360, 'resize': 'fit'}, 'thumb': {'w': 150, 'h': 150, 'resize': 'crop'},
                       'large': {'w': 480, 'h': 360, 'resize': 'fit'},
                       'medium': {'w': 480, 'h': 360, 'resize': 'fit'}}}]},
         'metadata': {'iso_language_code': 'en', 'result_type': 'recent'},
         'source': '<a href="http://shopblogs.net/blouse_king/" rel="nofollow">blouse_king tweeter</a>',
         'in_reply_to_status_id': None, 'in_reply_to_status_id_str': None, 'in_reply_to_user_id': None,
         'in_reply_to_user_id_str': None, 'in_reply_to_screen_name': None,
         'user': {'id': 2992352088, 'id_str': '2992352088', 'name': 'ブラウスの専門ショップ ブラウス・キング',
                  'screen_name': 'blouse_king', 'location': '',
                  'description': '激安ブラウスや、フォーマル・オフィス用のブラウス。チャイナブラウスもあります！', 'url': 'http://t.co/J3FVj3ExwB',
                  'entities': {'url': {'urls': [
                      {'url': 'http://t.co/J3FVj3ExwB', 'expanded_url': 'http://shopblogs.net/blouse_king/',
                       'display_url': 'shopblogs.net/blouse_king/', 'indices': [0, 22]}]}, 'description': {'urls': []}},
                  'protected': False, 'followers_count': 4397, 'friends_count': 5118, 'listed_count': 7,
                  'created_at': 'Thu Jan 22 13:31:52 +0000 2015', 'favourites_count': 0, 'utc_offset': None,
                  'time_zone': None, 'geo_enabled': False, 'verified': False, 'statuses_count': 10520, 'lang': 'ja',
                  'contributors_enabled': False, 'is_translator': False, 'is_translation_enabled': False,
                  'profile_background_color': '000000',
                  'profile_background_image_url': 'http://abs.twimg.com/images/themes/theme1/bg.png',
                  'profile_background_image_url_https': 'https://abs.twimg.com/images/themes/theme1/bg.png',
                  'profile_background_tile': False,
                  'profile_image_url': 'http://pbs.twimg.com/profile_images/558255920472276992/F5lbS8-V_normal.jpeg',
                  'profile_image_url_https': 'https://pbs.twimg.com/profile_images/558255920472276992/F5lbS8-V_normal.jpeg',
                  'profile_link_color': '333333', 'profile_sidebar_border_color': '000000',
                  'profile_sidebar_fill_color': '000000', 'profile_text_color': '000000',
                  'profile_use_background_image': False, 'has_extended_profile': False, 'default_profile': False,
                  'default_profile_image': False, 'following': False, 'follow_request_sent': False,
                  'notifications': False, 'translator_type': 'none'}, 'geo': None, 'coordinates': None, 'place': None,
         'contributors': None, 'is_quote_status': False, 'retweet_count': 0, 'favorite_count': 0, 'favorited': False,
         'retweeted': False, 'possibly_sensitive': False, 'lang': 'en'},
        {'created_at': 'Mon Oct 22 09:31:58 +0000 2018', 'id': 1054304346442096640, 'id_str': '1054304346442096640',
         'text': '@ChrisWesseling Pat Mahomes nick name should be Pat ‘mayhem’ mahomes. The Chiefs offense should be called the Kansa… https://t.co/RXsMa0KJ2S',
         'truncated': True, 'entities': {'hashtags': [], 'symbols': [], 'user_mentions': [
            {'screen_name': 'ChrisWesseling', 'name': 'Chris Wesseling', 'id': 43399264, 'id_str': '43399264',
             'indices': [0, 15]}], 'urls': [
            {'url': 'https://t.co/RXsMa0KJ2S', 'expanded_url': 'https://twitter.com/i/web/status/1054304346442096640',
             'display_url': 'twitter.com/i/web/status/1…', 'indices': [117, 140]}]},
         'metadata': {'iso_language_code': 'en', 'result_type': 'recent'},
         'source': '<a href="http://twitter.com/download/iphone" rel="nofollow">Twitter for iPhone</a>',
         'in_reply_to_status_id': None, 'in_reply_to_status_id_str': None, 'in_reply_to_user_id': 43399264,
         'in_reply_to_user_id_str': '43399264', 'in_reply_to_screen_name': 'ChrisWesseling',
         'user': {'id': 2503812053, 'id_str': '2503812053', 'name': 'Tayshaun Daphodil', 'screen_name': 'floseidon13',
                  'location': '', 'description': 'I enjoy ice cream and a nice pair of slacks', 'url': None,
                  'entities': {'description': {'urls': []}}, 'protected': False, 'followers_count': 69,
                  'friends_count': 104, 'listed_count': 0, 'created_at': 'Wed Apr 23 11:02:32 +0000 2014',
                  'favourites_count': 285, 'utc_offset': None, 'time_zone': None, 'geo_enabled': False,
                  'verified': False, 'statuses_count': 241, 'lang': 'en', 'contributors_enabled': False,
                  'is_translator': False, 'is_translation_enabled': False, 'profile_background_color': 'C0DEED',
                  'profile_background_image_url': 'http://abs.twimg.com/images/themes/theme1/bg.png',
                  'profile_background_image_url_https': 'https://abs.twimg.com/images/themes/theme1/bg.png',
                  'profile_background_tile': False,
                  'profile_image_url': 'http://pbs.twimg.com/profile_images/527959626810392577/QmUJ-nrb_normal.jpeg',
                  'profile_image_url_https': 'https://pbs.twimg.com/profile_images/527959626810392577/QmUJ-nrb_normal.jpeg',
                  'profile_link_color': '1DA1F2', 'profile_sidebar_border_color': 'C0DEED',
                  'profile_sidebar_fill_color': 'DDEEF6', 'profile_text_color': '333333',
                  'profile_use_background_image': True, 'has_extended_profile': False, 'default_profile': True,
                  'default_profile_image': False, 'following': False, 'follow_request_sent': False,
                  'notifications': False, 'translator_type': 'none'}, 'geo': None, 'coordinates': None, 'place': None,
         'contributors': None, 'is_quote_status': False, 'retweet_count': 0, 'favorite_count': 1, 'favorited': False,
         'retweeted': False, 'lang': 'en'},
        {'created_at': 'Mon Oct 22 09:29:06 +0000 2018', 'id': 1054303621809094656, 'id_str': '1054303621809094656',
         'text': '@FOX19DanW @Fox19Jessica @Fox19Rebecca @Bob_Herzog @SheilaGrayTV @TeraBlake @MeganMooreWKRC @RandiRicoWLWT… https://t.co/mTe3cS2Ypk',
         'truncated': True, 'entities': {'hashtags': [], 'symbols': [], 'user_mentions': [
            {'screen_name': 'FOX19DanW', 'name': 'Dan Wells', 'id': 20790690, 'id_str': '20790690', 'indices': [0, 10]},
            {'screen_name': 'Fox19Jessica', 'name': 'Jessica Brown', 'id': 763525957, 'id_str': '763525957',
             'indices': [11, 24]},
            {'screen_name': 'Fox19Rebecca', 'name': 'Rebecca Smith', 'id': 1470549038, 'id_str': '1470549038',
             'indices': [25, 38]},
            {'screen_name': 'Bob_Herzog', 'name': 'Bob Herzog', 'id': 114455520, 'id_str': '114455520',
             'indices': [39, 50]},
            {'screen_name': 'SheilaGrayTV', 'name': 'Sheila Gray', 'id': 21126909, 'id_str': '21126909',
             'indices': [51, 64]},
            {'screen_name': 'TeraBlake', 'name': 'Tera Blake', 'id': 191838034, 'id_str': '191838034',
             'indices': [65, 75]},
            {'screen_name': 'MeganMooreWKRC', 'name': 'Megan Moore', 'id': 637034929, 'id_str': '637034929',
             'indices': [76, 91]},
            {'screen_name': 'RandiRicoWLWT', 'name': 'Randi Rico WLWT', 'id': 43670834, 'id_str': '43670834',
             'indices': [92, 106]}], 'urls': [
            {'url': 'https://t.co/mTe3cS2Ypk', 'expanded_url': 'https://twitter.com/i/web/status/1054303621809094656',
             'display_url': 'twitter.com/i/web/status/1…', 'indices': [108, 131]}]},
         'metadata': {'iso_language_code': 'en', 'result_type': 'recent'},
         'source': '<a href="http://twitter.com/download/iphone" rel="nofollow">Twitter for iPhone</a>',
         'in_reply_to_status_id': None, 'in_reply_to_status_id_str': None, 'in_reply_to_user_id': 20790690,
         'in_reply_to_user_id_str': '20790690', 'in_reply_to_screen_name': 'FOX19DanW',
         'user': {'id': 218011593, 'id_str': '218011593', 'name': 'Adam Joseph Raper', 'screen_name': 'AdamJosephRaper',
                  'location': 'Lebanon, Ohio',
                  'description': 'GO COLTS! GO REDS! O-H-I-O! WHO-DEY! fantasy sports fanatic!', 'url': None,
                  'entities': {'description': {'urls': []}}, 'protected': False, 'followers_count': 62,
                  'friends_count': 654, 'listed_count': 0, 'created_at': 'Sun Nov 21 04:57:14 +0000 2010',
                  'favourites_count': 16, 'utc_offset': None, 'time_zone': None, 'geo_enabled': False,
                  'verified': False, 'statuses_count': 1767, 'lang': 'en', 'contributors_enabled': False,
                  'is_translator': False, 'is_translation_enabled': False, 'profile_background_color': 'C0DEED',
                  'profile_background_image_url': 'http://abs.twimg.com/images/themes/theme1/bg.png',
                  'profile_background_image_url_https': 'https://abs.twimg.com/images/themes/theme1/bg.png',
                  'profile_background_tile': False,
                  'profile_image_url': 'http://pbs.twimg.com/profile_images/924582807095169024/KMkIXRau_normal.jpg',
                  'profile_image_url_https': 'https://pbs.twimg.com/profile_images/924582807095169024/KMkIXRau_normal.jpg',
                  'profile_banner_url': 'https://pbs.twimg.com/profile_banners/218011593/1509272695',
                  'profile_link_color': '1DA1F2', 'profile_sidebar_border_color': 'C0DEED',
                  'profile_sidebar_fill_color': 'DDEEF6', 'profile_text_color': '333333',
                  'profile_use_background_image': True, 'has_extended_profile': False, 'default_profile': True,
                  'default_profile_image': False, 'following': False, 'follow_request_sent': False,
                  'notifications': False, 'translator_type': 'none'}, 'geo': None, 'coordinates': None, 'place': None,
         'contributors': None, 'is_quote_status': False, 'retweet_count': 0, 'favorite_count': 0, 'favorited': False,
         'retweeted': False, 'possibly_sensitive': False, 'lang': 'en'},
        {'created_at': 'Mon Oct 22 08:40:47 +0000 2018', 'id': 1054291464526725120, 'id_str': '1054291464526725120',
         'text': 'y Tyreek Hill pillo un TD...\nMe he quedado a un drop de zeke en la endzone de ganar los 170 pavis más ez de mi vida… https://t.co/ukxtIB0rnt',
         'truncated': True, 'entities': {'hashtags': [], 'symbols': [], 'user_mentions': [], 'urls': [
            {'url': 'https://t.co/ukxtIB0rnt', 'expanded_url': 'https://twitter.com/i/web/status/1054291464526725120',
             'display_url': 'twitter.com/i/web/status/1…', 'indices': [117, 140]}]},
         'metadata': {'iso_language_code': 'es', 'result_type': 'recent'},
         'source': '<a href="https://about.twitter.com/products/tweetdeck" rel="nofollow">TweetDeck</a>',
         'in_reply_to_status_id': 1054104169559285765, 'in_reply_to_status_id_str': '1054104169559285765',
         'in_reply_to_user_id': 47070304, 'in_reply_to_user_id_str': '47070304', 'in_reply_to_screen_name': 'Zapa41',
         'user': {'id': 47070304, 'id_str': '47070304', 'name': 'Asier 💀🎺', 'screen_name': 'Zapa41',
                  'location': 'San Adrian.', 'description': 'me dais pereza', 'url': None,
                  'entities': {'description': {'urls': []}}, 'protected': False, 'followers_count': 134,
                  'friends_count': 300, 'listed_count': 4, 'created_at': 'Sun Jun 14 10:27:37 +0000 2009',
                  'favourites_count': 4898, 'utc_offset': None, 'time_zone': None, 'geo_enabled': True,
                  'verified': False, 'statuses_count': 38050, 'lang': 'es', 'contributors_enabled': False,
                  'is_translator': False, 'is_translation_enabled': False, 'profile_background_color': '000000',
                  'profile_background_image_url': 'http://abs.twimg.com/images/themes/theme6/bg.gif',
                  'profile_background_image_url_https': 'https://abs.twimg.com/images/themes/theme6/bg.gif',
                  'profile_background_tile': False,
                  'profile_image_url': 'http://pbs.twimg.com/profile_images/1052247044310487040/_m0OtR6W_normal.jpg',
                  'profile_image_url_https': 'https://pbs.twimg.com/profile_images/1052247044310487040/_m0OtR6W_normal.jpg',
                  'profile_banner_url': 'https://pbs.twimg.com/profile_banners/47070304/1539674316',
                  'profile_link_color': '91D2FA', 'profile_sidebar_border_color': '000000',
                  'profile_sidebar_fill_color': 'A0C5C7', 'profile_text_color': '333333',
                  'profile_use_background_image': True, 'has_extended_profile': False, 'default_profile': False,
                  'default_profile_image': False, 'following': False, 'follow_request_sent': False,
                  'notifications': False, 'translator_type': 'none'}, 'geo': None, 'coordinates': None, 'place': None,
         'contributors': None, 'is_quote_status': False, 'retweet_count': 0, 'favorite_count': 1, 'favorited': False,
         'retweeted': False, 'lang': 'es'},
        {'created_at': 'Mon Oct 22 08:27:08 +0000 2018', 'id': 1054288030020841480, 'id_str': '1054288030020841480',
         'text': 'The Chiefs Are Saving the NFL’s 2018 Season https://t.co/G4LXMxyvdi', 'truncated': False,
         'entities': {'hashtags': [], 'symbols': [], 'user_mentions': [], 'urls': [
             {'url': 'https://t.co/G4LXMxyvdi', 'expanded_url': 'https://ift.tt/2NTxZHf',
              'display_url': 'ift.tt/2NTxZHf', 'indices': [44, 67]}]},
         'metadata': {'iso_language_code': 'en', 'result_type': 'recent'},
         'source': '<a href="https://ifttt.com" rel="nofollow">IFTTT</a>', 'in_reply_to_status_id': None,
         'in_reply_to_status_id_str': None, 'in_reply_to_user_id': None, 'in_reply_to_user_id_str': None,
         'in_reply_to_screen_name': None,
         'user': {'id': 290547439, 'id_str': '290547439', 'name': 'Sahara Jane', 'screen_name': 'imthesupersj',
                  'location': 'Republic of the Philippines',
                  'description': 'Psalm 27:1 🔱 Animus Invictus 🔱 Wanderlust 🔱 Semperjuvenescent 🔱 Storyteller 🔱 bohemian 🔱 #Catlover 🔱 Michael Jackson ● RDJ ● KB24 ● Lakers ● DLSU fan',
                  'url': 'https://t.co/djFJRE0sXw', 'entities': {'url': {'urls': [
                 {'url': 'https://t.co/djFJRE0sXw', 'expanded_url': 'https://instagram.com/imthesupersj',
                  'display_url': 'instagram.com/imthesupersj', 'indices': [0, 23]}]}, 'description': {'urls': []}},
                  'protected': False, 'followers_count': 2462, 'friends_count': 533, 'listed_count': 209,
                  'created_at': 'Sat Apr 30 13:25:19 +0000 2011', 'favourites_count': 8252, 'utc_offset': None,
                  'time_zone': None, 'geo_enabled': True, 'verified': False, 'statuses_count': 353969, 'lang': 'en',
                  'contributors_enabled': False, 'is_translator': False, 'is_translation_enabled': False,
                  'profile_background_color': '199CE3',
                  'profile_background_image_url': 'http://abs.twimg.com/images/themes/theme9/bg.gif',
                  'profile_background_image_url_https': 'https://abs.twimg.com/images/themes/theme9/bg.gif',
                  'profile_background_tile': False,
                  'profile_image_url': 'http://pbs.twimg.com/profile_images/1047713644346146816/Kl7pOP2G_normal.jpg',
                  'profile_image_url_https': 'https://pbs.twimg.com/profile_images/1047713644346146816/Kl7pOP2G_normal.jpg',
                  'profile_banner_url': 'https://pbs.twimg.com/profile_banners/290547439/1538650266',
                  'profile_link_color': '1B95E0', 'profile_sidebar_border_color': 'FFFFFF',
                  'profile_sidebar_fill_color': '252429', 'profile_text_color': '359475',
                  'profile_use_background_image': True, 'has_extended_profile': True, 'default_profile': False,
                  'default_profile_image': False, 'following': False, 'follow_request_sent': False,
                  'notifications': False, 'translator_type': 'regular'}, 'geo': None, 'coordinates': None,
         'place': None, 'contributors': None, 'is_quote_status': False, 'retweet_count': 0, 'favorite_count': 0,
         'favorited': False, 'retweeted': False, 'possibly_sensitive': False, 'lang': 'en'},
        {'created_at': 'Mon Oct 22 08:23:26 +0000 2018', 'id': 1054287099245936643, 'id_str': '1054287099245936643',
         'text': 'Chiefs fans comforts Tyreek Hill after dropped TD\nhttps://t.co/LKH1k5l9PX https://t.co/PSFQLuSblK',
         'truncated': False, 'entities': {'hashtags': [], 'symbols': [], 'user_mentions': [], 'urls': [
            {'url': 'https://t.co/LKH1k5l9PX', 'expanded_url': 'http://shopblogs.net/leather_wallet/b/1610578/',
             'display_url': 'shopblogs.net/leather_wallet…', 'indices': [50, 73]}], 'media': [
            {'id': 1054287098167980033, 'id_str': '1054287098167980033', 'indices': [74, 97],
             'media_url': 'http://pbs.twimg.com/media/DqGUh6mUcAE3ivq.jpg',
             'media_url_https': 'https://pbs.twimg.com/media/DqGUh6mUcAE3ivq.jpg', 'url': 'https://t.co/PSFQLuSblK',
             'display_url': 'pic.twitter.com/PSFQLuSblK',
             'expanded_url': 'https://twitter.com/leather_wallet1/status/1054287099245936643/photo/1', 'type': 'photo',
             'sizes': {'thumb': {'w': 150, 'h': 150, 'resize': 'crop'}, 'small': {'w': 480, 'h': 360, 'resize': 'fit'},
                       'medium': {'w': 480, 'h': 360, 'resize': 'fit'},
                       'large': {'w': 480, 'h': 360, 'resize': 'fit'}}}]}, 'extended_entities': {'media': [
            {'id': 1054287098167980033, 'id_str': '1054287098167980033', 'indices': [74, 97],
             'media_url': 'http://pbs.twimg.com/media/DqGUh6mUcAE3ivq.jpg',
             'media_url_https': 'https://pbs.twimg.com/media/DqGUh6mUcAE3ivq.jpg', 'url': 'https://t.co/PSFQLuSblK',
             'display_url': 'pic.twitter.com/PSFQLuSblK',
             'expanded_url': 'https://twitter.com/leather_wallet1/status/1054287099245936643/photo/1', 'type': 'photo',
             'sizes': {'thumb': {'w': 150, 'h': 150, 'resize': 'crop'}, 'small': {'w': 480, 'h': 360, 'resize': 'fit'},
                       'medium': {'w': 480, 'h': 360, 'resize': 'fit'},
                       'large': {'w': 480, 'h': 360, 'resize': 'fit'}}}]},
         'metadata': {'iso_language_code': 'en', 'result_type': 'recent'},
         'source': '<a href="http://shopblogs.net/sandal/" rel="nofollow">sandal tweeter</a>',
         'in_reply_to_status_id': None, 'in_reply_to_status_id_str': None, 'in_reply_to_user_id': None,
         'in_reply_to_user_id_str': None, 'in_reply_to_screen_name': None,
         'user': {'id': 3039815370, 'id_str': '3039815370', 'name': '革財布専門サイト スティングレー',
                  'screen_name': 'leather_wallet1', 'location': '', 'description': '革財布だけを専門に扱っています。エイ革やパイソン革などもあります。',
                  'url': 'http://t.co/SsUfT6wIIy', 'entities': {'url': {'urls': [
                 {'url': 'http://t.co/SsUfT6wIIy', 'expanded_url': 'http://shopblogs.net/leather_wallet/',
                  'display_url': 'shopblogs.net/leather_wallet/', 'indices': [0, 22]}]}, 'description': {'urls': []}},
                  'protected': False, 'followers_count': 7583, 'friends_count': 7998, 'listed_count': 7,
                  'created_at': 'Tue Feb 24 15:44:18 +0000 2015', 'favourites_count': 0, 'utc_offset': None,
                  'time_zone': None, 'geo_enabled': False, 'verified': False, 'statuses_count': 10712, 'lang': 'ja',
                  'contributors_enabled': False, 'is_translator': False, 'is_translation_enabled': False,
                  'profile_background_color': '000000',
                  'profile_background_image_url': 'http://abs.twimg.com/images/themes/theme1/bg.png',
                  'profile_background_image_url_https': 'https://abs.twimg.com/images/themes/theme1/bg.png',
                  'profile_background_tile': False,
                  'profile_image_url': 'http://pbs.twimg.com/profile_images/570248025595842560/p4vxKqa0_normal.jpeg',
                  'profile_image_url_https': 'https://pbs.twimg.com/profile_images/570248025595842560/p4vxKqa0_normal.jpeg',
                  'profile_link_color': '002999', 'profile_sidebar_border_color': '000000',
                  'profile_sidebar_fill_color': '000000', 'profile_text_color': '000000',
                  'profile_use_background_image': False, 'has_extended_profile': False, 'default_profile': False,
                  'default_profile_image': False, 'following': False, 'follow_request_sent': False,
                  'notifications': False, 'translator_type': 'none'}, 'geo': None, 'coordinates': None, 'place': None,
         'contributors': None, 'is_quote_status': False, 'retweet_count': 0, 'favorite_count': 0, 'favorited': False,
         'retweeted': False, 'possibly_sensitive': False, 'lang': 'en'}]
